-- Stranke
CREATE TABLE neoj_customers (
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR2(100) NOT NULL
);

-- Produkti
CREATE TABLE neoj_products (
    product_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR2(100) NOT NULL,
    description  VARCHAR2(200),
    price        NUMBER(10,2) NOT NULL
);

-- Naročila
CREATE TABLE neoj_orders (
    order_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id  NUMBER NOT NULL,
    status       VARCHAR2(20) DEFAULT 'ACTIVE',
    created_at   DATE DEFAULT SYSDATE,
    FOREIGN KEY (customer_id) REFERENCES neoj_customers(customer_id)
);

-- Postavke naro�il
CREATE TABLE neoj_order_items (
    order_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      NUMBER NOT NULL,
    product_id    NUMBER NOT NULL,
    quantity      NUMBER DEFAULT 1,
    unit_price    NUMBER(10,2) NOT NULL,
    FOREIGN KEY (order_id) REFERENCES neoj_orders(order_id),
    FOREIGN KEY (product_id) REFERENCES neoj_products(product_id)
);

-- Ra�uni
CREATE TABLE neoj_invoices (
    invoice_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     NUMBER NOT NULL,
    created_at   DATE DEFAULT SYSDATE,
    FOREIGN KEY (order_id) REFERENCES neoj_orders(order_id)
);

-- Postavke ra�unov
CREATE TABLE neoj_invoice_items (
    invoice_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id      NUMBER NOT NULL,
    product_id      NUMBER NOT NULL,
    quantity        NUMBER,
    unit_price      NUMBER(10,2),
    FOREIGN KEY (invoice_id) REFERENCES neoj_invoices(invoice_id),
    FOREIGN KEY (product_id) REFERENCES neoj_products(product_id)
);

CREATE SEQUENCE neoj_order_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE neoj_invoice_seq START WITH 1 INCREMENT BY 1;

-- Uvoz struktur
-- drop table neoj_apex_structure;
-- neoj_apex_export


create table neoj_apex_structure(
        jobid number,
        dbName varchar2(255) not null,
        application_id number not null,
        page_id number not null, 
        REGION_ID number not null,
		project_name varchar2(255) not null,
        application_name varchar2(255),
        page_name varchar2(255),
        region_name varchar2(255),
        table_owner varchar2(255),
        table_name varchar2(255),
        query_type varchar2(255),
        region_source  varchar2(255),
        source_type  varchar2(255)
);



create unique index neoj_apex_structure_pk on neoj_apex_structure(jobid, dbName,  application_id, page_id, REGION_ID);

alter table neoj_apex_structure add constraint neoj_apex_structure_pk primary key (jobid, dbName,  application_id, page_id, REGION_ID);

create sequence neoj_apex_structure_seq ;

create table neoj_apex_structure_tables(
        jobid number,
        dbName varchar2(255) not null,
        application_id number not null,
        page_id number not null, 
        REGION_ID number not null,
		project_name varchar2(255) not null,
        table_owner varchar2(255),
        table_name varchar2(255),
        table_type varchar2(255) 
);

create unique index neoj_apex_structure_tables_pk on neoj_apex_structure_tables(jobid, dbName,  application_id, page_id, REGION_ID,table_owner ,table_name);

alter table neoj_apex_structure_tables add constraint neoj_apex_structure_tables_pk primary key (jobid, dbName,  application_id, page_id, REGION_ID,table_owner ,table_name);

CREATE TABLE neoj_apex_export (
    id number generated by default as identity primary key,
    jobid       NUMBER ,
    jobid_orig       NUMBER ,
    created_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    payload     CLOB NOT NULL,
    master_job_id   number,
    export_type     varchar2(50),
    cypher          clob,
    file_create     clob,
    status          varchar2(30),
    error_message   clob,
    started_at      timestamp,
    processed_at    timestamp,
    retry_count     number default 0  
);



alter table neoj_apex_export add constraint neoj_apex_export_uk unique  (jobid);



CREATE TABLE neoj_apex_exceptions(    
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jobid NUMBER NOT NULL,
    package_name VARCHAR2(255) NOT NULL,
    procedure_name VARCHAR2(255),
    exception_id VARCHAR2(255),
    err_msg VARCHAR2(3200),
    created_on DATE,
    created_by VARCHAR2(255)
);

-- If you want to make sure that the ID is always populated, even if a value is provided by an insert statement, use the following trigger instead:

CREATE OR REPLACE TRIGGER neoj_apex_exceptions_bir
BEFORE INSERT ON neoj_apex_exceptions
FOR EACH ROW
BEGIN
    :new.created_on:=sysdate;
    :new.created_by:=user;
END;
/



-- =============================================================================
-- Content: APEX TO NEO4J BUTTONS STURCTURE
-- Description: Stores APEX application page buttons with their associated
--              dynamic actions and action details.
-- =============================================================================


CREATE TABLE neoj_apex_buttons (
  jobid               NUMBER         NOT NULL,
  dbname              VARCHAR2(100),
  project_name        VARCHAR2(255),
  workspace           VARCHAR2(255),
  application_id      NUMBER         NOT NULL,
  application_name    VARCHAR2(255),
  page_id             NUMBER         NOT NULL,
  page_name           VARCHAR2(255),
  button_id           VARCHAR2(100)  NOT NULL,
  button_sequence     NUMBER,
  button_name         VARCHAR2(255),
  label               VARCHAR2(4000),
  button_action       VARCHAR2(255),
  button_action_code  VARCHAR2(4000),
  last_updated_by     VARCHAR2(255),
  last_updated_on     DATE,
  CONSTRAINT neoj_apex_buttons_pk
    PRIMARY KEY (jobid, application_id, page_id, button_id)
);

CREATE TABLE neoj_apex_dynamic_actions (
  jobid               NUMBER         NOT NULL,
  dbname              VARCHAR2(100),
  project_name        VARCHAR2(255),
  workspace           VARCHAR2(255),
  application_id      NUMBER         NOT NULL,
  application_name    VARCHAR2(255),
  page_id             NUMBER         NOT NULL,
  page_name           VARCHAR2(255),
  dynamic_action_id   VARCHAR2(100)  NOT NULL,
  dynamic_action_name VARCHAR2(255),
  dynamic_action_seq  NUMBER,
  when_selection_type VARCHAR2(255),
  when_event_name     VARCHAR2(255),
  last_updated_by     VARCHAR2(255),
  last_updated_on     DATE,
  CONSTRAINT neoj_apex_da_pk
    PRIMARY KEY (jobid, application_id, page_id, dynamic_action_id)
);

CREATE TABLE neoj_apex_dynamic_action_acts (
  jobid                        NUMBER         NOT NULL,
  dbname                       VARCHAR2(100),
  project_name                 VARCHAR2(255),
  workspace                    VARCHAR2(255),
  application_id               NUMBER         NOT NULL,
  page_id                      NUMBER         NOT NULL,
  dynamic_action_id            VARCHAR2(100)  NOT NULL,
  action_id                    VARCHAR2(100)  NOT NULL,
  action_name                  VARCHAR2(255),
  action_sequence              NUMBER,
  dynamic_action_event_result  VARCHAR2(255),
  execute_on_page_init         VARCHAR2(10),
  attribute_01                 VARCHAR2(4000),
  attribute_02                 VARCHAR2(4000),
  attribute_03                 VARCHAR2(4000),
  attribute_04                 VARCHAR2(4000),
  attribute_05                 VARCHAR2(4000),
  attribute_06                 VARCHAR2(4000),
  attribute_07                 VARCHAR2(4000),
  attribute_08                 VARCHAR2(4000),
  attribute_09                 VARCHAR2(4000),
  attribute_10                 VARCHAR2(4000),
  attribute_11                 VARCHAR2(4000),
  attribute_12                 VARCHAR2(4000),
  attribute_13                 VARCHAR2(4000),
  attribute_14                 VARCHAR2(4000),
  attribute_15                 VARCHAR2(4000),
  stop_execution_on_error      VARCHAR2(10),
  wait_for_result              VARCHAR2(10),
  last_updated_by              VARCHAR2(255),
  last_updated_on              DATE,
  CONSTRAINT neoj_apex_da_acts_pk
    PRIMARY KEY (jobid, application_id, page_id, dynamic_action_id, action_id)
);

CREATE TABLE neoj_apex_da_act_links (
  jobid               NUMBER         NOT NULL,
  dbname              VARCHAR2(100),
  project_name        VARCHAR2(255),
  workspace           VARCHAR2(255),
  application_id      NUMBER         NOT NULL,
  page_id             NUMBER         NOT NULL,
  dynamic_action_id   VARCHAR2(100)  NOT NULL,
  action_id           VARCHAR2(100)  NOT NULL,
  link_type           VARCHAR2(30)   NOT NULL,
  CONSTRAINT neoj_apex_da_act_links_pk
    PRIMARY KEY (jobid, application_id, page_id, dynamic_action_id, action_id, link_type)
);



CREATE TABLE neoj_apex_page_processes (
  jobid                  NUMBER         NOT NULL,
  dbname                 VARCHAR2(100),
  project_name           VARCHAR2(255),
  workspace              VARCHAR2(255),
  application_id         NUMBER         NOT NULL,
  application_name       VARCHAR2(255),
  page_id                NUMBER         NOT NULL,
  page_name              VARCHAR2(255),
  process_id             VARCHAR2(100)  NOT NULL,
  process_name           VARCHAR2(255),
  execution_sequence     NUMBER,
  process_point          VARCHAR2(255),
  process_point_code     VARCHAR2(255),
  process_type           VARCHAR2(255),
  process_type_code      VARCHAR2(255),
  process_source         CLOB,
  process_source_language VARCHAR2(255),
  condition_type         VARCHAR2(255),
  condition_type_code    VARCHAR2(255),
  condition_expression1  VARCHAR2(4000),
  condition_expression2  VARCHAR2(4000),
  when_button_pressed    VARCHAR2(255),
  when_button_pressed_id VARCHAR2(100),
  region_id              VARCHAR2(100),
  region_name            VARCHAR2(255),
  last_updated_by        VARCHAR2(255),
  last_updated_on        DATE,
  CONSTRAINT neoj_apex_page_proc_pk
    PRIMARY KEY (jobid, application_id, page_id, process_id)
);

CREATE TABLE neoj_apex_button_process_links (
  jobid                  NUMBER         NOT NULL,
  dbname                 VARCHAR2(100),
  project_name           VARCHAR2(255),
  workspace              VARCHAR2(255),
  application_id         NUMBER         NOT NULL,
  page_id                NUMBER         NOT NULL,
  button_id              VARCHAR2(100)  NOT NULL,
  process_id             VARCHAR2(100)  NOT NULL,
  link_type              VARCHAR2(30)   NOT NULL,
  CONSTRAINT neoj_apex_btn_proc_lnk_pk
    PRIMARY KEY (jobid, application_id, page_id, button_id, process_id, link_type)
);

CREATE TABLE neoj_apex_button_da_links (
  jobid               NUMBER         NOT NULL,
  dbname              VARCHAR2(100),
  project_name        VARCHAR2(255),
  workspace           VARCHAR2(255),
  application_id      NUMBER         NOT NULL,
  page_id             NUMBER         NOT NULL,
  button_id           VARCHAR2(100)  NOT NULL,
  dynamic_action_id   VARCHAR2(100)  NOT NULL,
  when_event_name     VARCHAR2(255),
  when_button         VARCHAR2(255),
  link_type           VARCHAR2(30)   NOT NULL,
  CONSTRAINT neoj_apex_btn_da_lnk_pk
    PRIMARY KEY (jobid, application_id, page_id, button_id, dynamic_action_id, link_type)
);



CREATE TABLE neoj_apex_button_act_links (
  jobid               NUMBER         NOT NULL,
  dbname              VARCHAR2(100),
  project_name        VARCHAR2(255),
  workspace           VARCHAR2(255),
  application_id      NUMBER         NOT NULL,
  page_id             NUMBER         NOT NULL,
  button_id           VARCHAR2(100)  NOT NULL,
  dynamic_action_id   VARCHAR2(100)  NOT NULL,
  action_id           VARCHAR2(100)  NOT NULL,
  link_type           VARCHAR2(30)   NOT NULL,
  CONSTRAINT neoj_apex_btn_act_lnk_pk
    PRIMARY KEY (
      jobid,
      application_id,
      page_id,
      button_id,
      dynamic_action_id,
      action_id,
      link_type
    )
);



CREATE INDEX neoj_apex_buttons_i1
  ON neoj_apex_buttons (jobid, application_id, page_id);

CREATE INDEX neoj_apex_da_i1
  ON neoj_apex_dynamic_actions (jobid, application_id, page_id);

CREATE INDEX neoj_apex_da_acts_i1
  ON neoj_apex_dynamic_action_acts (jobid, application_id, page_id, dynamic_action_id);

CREATE INDEX neoj_apex_da_act_links_i1
  ON neoj_apex_da_act_links (jobid, application_id, page_id, dynamic_action_id);

-- =============================================================================
-- Content: APEX TO NEO4J BUTTONS STURCTURE
-- =============================================================================



DECLARE
  l_clob CLOB;
BEGIN
  apex_json.initialize_clob_output;

  apex_json.open_object;
  apex_json.open_array('data');

  FOR rec IN (
    SELECT
      jobid,
      dbName,
      application_id,
      application_name,
      page_id,
      page_name,
      region_id,
      region_name,
      query_type,
      source_type,
      region_source,
      referenced_owner,
      referenced_name,
      referenced_type,
      table_owner,
      table_name
    FROM neoj_apex_structure
    WHERE jobid = :JOBID   -- <=== bind variable in SQL Workshop
    ORDER BY application_id, page_id, region_id
  )
  LOOP
    apex_json.open_object;

    apex_json.write('jobid',           rec.jobid);
    apex_json.write('dbName',          rec.dbName);
    apex_json.write('applicationId',   rec.application_id);
    apex_json.write('applicationName', rec.application_name);
    apex_json.write('pageId',          rec.page_id);
    apex_json.write('pageName',        rec.page_name);
    apex_json.write('regionId',        rec.region_id);
    apex_json.write('regionName',      rec.region_name);
    apex_json.write('queryType',       rec.query_type);
    apex_json.write('sourceType',      rec.source_type);
    apex_json.write('regionSource',    rec.region_source);

    apex_json.write('referencedOwner', rec.referenced_owner);
    apex_json.write('referencedName',  rec.referenced_name);
    apex_json.write('referencedType',  rec.referenced_type);

    apex_json.write('tableOwner',      rec.table_owner);

    apex_json.open_array('tableNames');
    IF rec.table_name IS NOT NULL AND rec.table_name NOT IN ('-', ' ') THEN
      FOR t IN (
        SELECT trim(regexp_substr(rec.table_name, '[^,]+', 1, level)) AS tname
        FROM dual
        CONNECT BY regexp_substr(rec.table_name, '[^,]+', 1, level) IS NOT NULL
      ) LOOP
        apex_json.write(t.tname);
      END LOOP;
    END IF;
    apex_json.close_array;

    apex_json.close_object;
  END LOOP;

  apex_json.close_array; -- data
  apex_json.close_object;

  l_clob := apex_json.get_clob_output;
  apex_json.free_output;

  MERGE INTO neoj_apex_export e
  USING (SELECT :JOBID AS jobid FROM dual) s
  ON (e.jobid = s.jobid)
  WHEN MATCHED THEN
    UPDATE SET e.payload = l_clob, e.created_at = SYSTIMESTAMP
  WHEN NOT MATCHED THEN
    INSERT (jobid, payload) VALUES (:JOBID, l_clob);

END;
/


CREATE TABLE neoj_ora_package_procedure (
    -- Job / context
    jobid               NUMBER          NOT NULL,
    dbname              VARCHAR2(128),
    project_name        VARCHAR2(256),

    -- Source package (where the CALL was found)
    source_owner        VARCHAR2(128),
    source_package      VARCHAR2(128),
    source_procedure    VARCHAR2(128),   -- procedure containing the call
    source_line         NUMBER,          -- line number from ALL_IDENTIFIERS

    -- Called package/procedure
    owner               VARCHAR2(128),
    object_name         VARCHAR2(128),   -- package name
    procedure_name      VARCHAR2(128),   -- procedure/function name

    -- Computed full names
    source_full_name    VARCHAR2(512),   -- dbname.owner.package.procedure
    object_full_name    VARCHAR2(512),   -- dbname.owner.package
    procedure_full_name VARCHAR2(512),   -- dbname.owner.package.procedure

    -- Metadata
    last_updated_by     VARCHAR2(128)    DEFAULT USER,
    last_updated_on     DATE             DEFAULT SYSDATE,
    usage varchar2(255),

    CONSTRAINT pk_neoj_ora_pkg_prc PRIMARY KEY (jobid, source_owner, source_package, source_procedure, owner, object_name, procedure_name)
);

alter table Y055490.NEOJ_ORA_PACKAGE_PROCEDURE add SIGNATURE varchar2(4000 byte);
alter table Y055490.NEOJ_ORA_PACKAGE_PROCEDURE add SOURCE_SIGNATURE varchar2(4000 byte);

CREATE INDEX idx_neoj_ora_pkg_prc_job    ON neoj_ora_package_procedure (jobid);
CREATE INDEX idx_neoj_ora_pkg_prc_src    ON neoj_ora_package_procedure (source_owner, source_package);
CREATE INDEX idx_neoj_ora_pkg_prc_called ON neoj_ora_package_procedure (owner, object_name, procedure_name);


create table neoj_ora_package_procedure_crud (
    jobid                number,
    dbname               varchar2(128),
    project_name         varchar2(200),
    package_owner        varchar2(128),
    package_name         varchar2(128),
    procedure_name       varchar2(128),
    proc_start_line      number,
    proc_end_line        number,
    source_line          number,
    table_owner          varchar2(128),
    table_name           varchar2(128),
    ref_type             varchar2(30),
    dml_type             varchar2(30),
    source_text          varchar2(4000),
    package_full_name    varchar2(400),
    procedure_full_name  varchar2(500),
    object_full_name     varchar2(400),
    last_updated_by      varchar2(255),
    last_updated_on      date
);


create unique index neoj_ora_pkg_prc_crud_u1
    on neoj_ora_package_procedure_crud (
        jobid,
        package_owner,
        package_name,
        procedure_name,
        source_line,
        table_owner,
        table_name,
        nvl(dml_type, '?')
    );
    
    
    

CREATE TABLE ME_CODES (CODE_GROUP VARCHAR2(255) NOT NULL, CODE VARCHAR2(255) NOT NULL, CODE_VALUE VARCHAR2(255) NOT NULL);

CREATE UNIQUE INDEX ME_CODES_PK ON ME_CODES(CODE_GROUP, CODE);

/* =========================================================
   ME_LEGACY_APP_STATUS
   ========================================================= */
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ME_LEGACY_APP_STATUS','IDENTIFIED','IDENTIFIED');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ME_LEGACY_APP_STATUS','IN_ANALYSIS','IN_ANALYSIS');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ME_LEGACY_APP_STATUS','IN_SCOPE','IN_SCOPE');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ME_LEGACY_APP_STATUS','PARTIALLY_MIGRATED','PARTIALLY_MIGRATED');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ME_LEGACY_APP_STATUS','MIGRATED','MIGRATED');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ME_LEGACY_APP_STATUS','ON_HOLD','ON_HOLD');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ME_LEGACY_APP_STATUS','OUT_OF_SCOPE','OUT_OF_SCOPE');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ME_LEGACY_APP_STATUS','RETIRED','RETIRED');


/* =========================================================
   ME_MIG_CASE_STATUS
   ========================================================= */
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ME_MIG_CASE_STATUS','DRAFT','DRAFT');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ME_MIG_CASE_STATUS','IDENTIFIED','IDENTIFIED');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ME_MIG_CASE_STATUS','ANALYSING','ANALYSING');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ME_MIG_CASE_STATUS','READY_FOR_DECISION','READY_FOR_DECISION');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ME_MIG_CASE_STATUS','APPROVED','APPROVED');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ME_MIG_CASE_STATUS','IN_IMPLEMENTATION','IN_IMPLEMENTATION');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ME_MIG_CASE_STATUS','IN_TEST','IN_TEST');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ME_MIG_CASE_STATUS','DONE','DONE');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ME_MIG_CASE_STATUS','ON_HOLD','ON_HOLD');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ME_MIG_CASE_STATUS','REJECTED','REJECTED');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ME_MIG_CASE_STATUS','CANCELLED','CANCELLED');


/* =========================================================
   ME_MIG_CASE_DECISION_TYPE
   ========================================================= */
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ME_MIG_CASE_DECISION_TYPE','REBUILD_IN_APEX','REBUILD_IN_APEX');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ME_MIG_CASE_DECISION_TYPE','REPLACE_WITH_STANDARD_APEX','REPLACE_WITH_STANDARD_APEX');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ME_MIG_CASE_DECISION_TYPE','REPLACE_WITH_OTHER_SYSTEM','REPLACE_WITH_OTHER_SYSTEM');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ME_MIG_CASE_DECISION_TYPE','KEEP_AS_IS','KEEP_AS_IS');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ME_MIG_CASE_DECISION_TYPE','DROP','DROP');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ME_MIG_CASE_DECISION_TYPE','POSTPONE','POSTPONE');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ME_MIG_CASE_DECISION_TYPE','UNKNOWN','UNKNOWN');


/* =========================================================
   ORA_BLOCK_MIG_STATUS
   ========================================================= */
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_BLOCK_MIG_STATUS','NOT_ANALYSED','NOT_ANALYSED');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_BLOCK_MIG_STATUS','ANALYSED','ANALYSED');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_BLOCK_MIG_STATUS','MAPPED','MAPPED');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_BLOCK_MIG_STATUS','READY_FOR_BUILD','READY_FOR_BUILD');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_BLOCK_MIG_STATUS','IN_BUILD','IN_BUILD');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_BLOCK_MIG_STATUS','IN_TEST','IN_TEST');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_BLOCK_MIG_STATUS','MIGRATED','MIGRATED');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_BLOCK_MIG_STATUS','PARTIALLY_MIGRATED','PARTIALLY_MIGRATED');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_BLOCK_MIG_STATUS','ON_HOLD','ON_HOLD');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_BLOCK_MIG_STATUS','NOT_IN_SCOPE','NOT_IN_SCOPE');


/* =========================================================
   ORA_BLOCK_MIG_BLOCK_TYPE
   ========================================================= */
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_BLOCK_MIG_BLOCK_TYPE','DATA_BLOCK','DATA_BLOCK');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_BLOCK_MIG_BLOCK_TYPE','CONTROL_BLOCK','CONTROL_BLOCK');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_BLOCK_MIG_BLOCK_TYPE','DISPLAY_BLOCK','DISPLAY_BLOCK');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_BLOCK_MIG_BLOCK_TYPE','PARAMETER_BLOCK','PARAMETER_BLOCK');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_BLOCK_MIG_BLOCK_TYPE','UNKNOWN','UNKNOWN');


/* =========================================================
   ORA_CODE_OBJECT_MIG_STATUS
   ========================================================= */
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_CODE_OBJECT_MIG_STATUS','NOT_ANALYSED','NOT_ANALYSED');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_CODE_OBJECT_MIG_STATUS','ANALYSED','ANALYSED');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_CODE_OBJECT_MIG_STATUS','MAPPED','MAPPED');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_CODE_OBJECT_MIG_STATUS','READY_FOR_BUILD','READY_FOR_BUILD');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_CODE_OBJECT_MIG_STATUS','IN_BUILD','IN_BUILD');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_CODE_OBJECT_MIG_STATUS','IN_TEST','IN_TEST');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_CODE_OBJECT_MIG_STATUS','MIGRATED','MIGRATED');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_CODE_OBJECT_MIG_STATUS','PARTIALLY_MIGRATED','PARTIALLY_MIGRATED');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_CODE_OBJECT_MIG_STATUS','ON_HOLD','ON_HOLD');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_CODE_OBJECT_MIG_STATUS','NOT_IN_SCOPE','NOT_IN_SCOPE');


/* =========================================================
   ORA_CODE_OBJECT_TYPE
   ========================================================= */
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_CODE_OBJECT_TYPE','BUTTON','BUTTON');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_CODE_OBJECT_TYPE','TRIGGER','TRIGGER');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_CODE_OBJECT_TYPE','FORM_PROCEDURE','FORM_PROCEDURE');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_CODE_OBJECT_TYPE','FORM_FUNCTION','FORM_FUNCTION');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_CODE_OBJECT_TYPE','PROGRAM_UNIT','PROGRAM_UNIT');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_CODE_OBJECT_TYPE','MENU_ACTION','MENU_ACTION');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_CODE_OBJECT_TYPE','OTHER','OTHER');


/* =========================================================
   ORA_CODE_OBJECT_SCOPE_TYPE
   ========================================================= */
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_CODE_OBJECT_SCOPE_TYPE','FORM','FORM');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_CODE_OBJECT_SCOPE_TYPE','BLOCK','BLOCK');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_CODE_OBJECT_SCOPE_TYPE','ITEM','ITEM');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_CODE_OBJECT_SCOPE_TYPE','GLOBAL','GLOBAL');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_CODE_OBJECT_SCOPE_TYPE','MENU','MENU');


/* =========================================================
   ORA_FORM_MIG_STATUS
   ========================================================= */
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_FORM_MIG_STATUS','NOT_ANALYSED','NOT_ANALYSED');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_FORM_MIG_STATUS','ANALYSED','ANALYSED');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_FORM_MIG_STATUS','MAPPED','MAPPED');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_FORM_MIG_STATUS','READY_FOR_BUILD','READY_FOR_BUILD');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_FORM_MIG_STATUS','IN_BUILD','IN_BUILD');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_FORM_MIG_STATUS','IN_TEST','IN_TEST');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_FORM_MIG_STATUS','MIGRATED','MIGRATED');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_FORM_MIG_STATUS','PARTIALLY_MIGRATED','PARTIALLY_MIGRATED');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_FORM_MIG_STATUS','ON_HOLD','ON_HOLD');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_FORM_MIG_STATUS','NOT_IN_SCOPE','NOT_IN_SCOPE');

