-- Stranke
CREATE TABLE neoj_customers (
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR2(100) NOT NULL
);

-- Produkti
CREATE TABLE neoj_products (
    product_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR2(100) NOT NULL,
    description  VARCHAR2(200),
    price        NUMBER(10,2) NOT NULL
);

-- Naročila
CREATE TABLE neoj_orders (
    order_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id  NUMBER NOT NULL,
    status       VARCHAR2(20) DEFAULT 'ACTIVE',
    created_at   DATE DEFAULT SYSDATE,
    FOREIGN KEY (customer_id) REFERENCES neoj_customers(customer_id)
);

-- Postavke naro�il
CREATE TABLE neoj_order_items (
    order_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      NUMBER NOT NULL,
    product_id    NUMBER NOT NULL,
    quantity      NUMBER DEFAULT 1,
    unit_price    NUMBER(10,2) NOT NULL,
    FOREIGN KEY (order_id) REFERENCES neoj_orders(order_id),
    FOREIGN KEY (product_id) REFERENCES neoj_products(product_id)
);

-- Ra�uni
CREATE TABLE neoj_invoices (
    invoice_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     NUMBER NOT NULL,
    created_at   DATE DEFAULT SYSDATE,
    FOREIGN KEY (order_id) REFERENCES neoj_orders(order_id)
);

-- Postavke ra�unov
CREATE TABLE neoj_invoice_items (
    invoice_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id      NUMBER NOT NULL,
    product_id      NUMBER NOT NULL,
    quantity        NUMBER,
    unit_price      NUMBER(10,2),
    FOREIGN KEY (invoice_id) REFERENCES neoj_invoices(invoice_id),
    FOREIGN KEY (product_id) REFERENCES neoj_products(product_id)
);

CREATE SEQUENCE neoj_order_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE neoj_invoice_seq START WITH 1 INCREMENT BY 1;

