CREATE OR REPLACE TRIGGER NEOJ_ORDERS_TRG
BEFORE INSERT OR UPDATE OR DELETE
ON NEOJ_ORDERS
FOR EACH ROW
BEGIN
    -- Trigger logic here
    IF INSERTING THEN
        :NEW.order_id:=NEOJ_ORDER_SEQ.NEXTVAL;
        IF :NEW.status IS NULL THEN
            :NEW.status:='ACTIVE';
        END IF;
        IF :NEW.created_at IS NULL THEN
            :NEW.created_at:=SYSDATE;
        END IF;
    ELSIF UPDATING THEN
        NULL;
    ELSIF DELETING THEN
        NULL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER NEOJ_INVOICES_TRG
BEFORE INSERT OR UPDATE OR DELETE
ON NEOJ_INVOICES
FOR EACH ROW
BEGIN
    -- Trigger logic here
    IF INSERTING THEN
        :NEW.order_id:=NEOJ_INVOICE_SEQ.NEXTVAL;
    ELSIF UPDATING THEN
        NULL;
    ELSIF DELETING THEN
        NULL;
    END IF;
END;
/