-- Uvoz struktur
-- drop table neoj_apex_structure;
-- neoj_apex_export


create table neoj_apex_structure(
        jobid number,
        dbName varchar2(255) not null,
        application_id number not null,
        page_id number not null, 
        REGION_ID number not null,
		project_name varchar2(255) not null,
        application_name varchar2(255),
        page_name varchar2(255),
        region_name varchar2(255),
        table_owner varchar2(255),
        table_name varchar2(255),
        query_type varchar2(255),
        region_source  varchar2(255),
        source_type  varchar2(255)
);



create unique index neoj_apex_structure_pk on neoj_apex_structure(jobid, dbName,  application_id, page_id, REGION_ID);

alter table neoj_apex_structure add constraint neoj_apex_structure_pk primary key (jobid, dbName,  application_id, page_id, REGION_ID);

create sequence neoj_apex_structure_seq ;

create table neoj_apex_structure_tables(
        jobid number,
        dbName varchar2(255) not null,
        application_id number not null,
        page_id number not null, 
        REGION_ID number not null,
		project_name varchar2(255) not null,
        table_owner varchar2(255),
        table_name varchar2(255),
        table_type varchar2(255) 
);

create unique index neoj_apex_structure_tables_pk on neoj_apex_structure_tables(jobid, dbName,  application_id, page_id, REGION_ID,table_owner ,table_name);

alter table neoj_apex_structure_tables add constraint neoj_apex_structure_tables_pk primary key (jobid, dbName,  application_id, page_id, REGION_ID,table_owner ,table_name);

CREATE TABLE neoj_apex_export (
    id number generated by default as identity primary key,
    jobid       NUMBER ,
    jobid_orig       NUMBER ,
    created_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    payload     CLOB NOT NULL,
    master_job_id   number,
    export_type     varchar2(50),
    cypher          clob,
    file_create     clob,
    status          varchar2(30),
    error_message   clob,
    started_at      timestamp,
    processed_at    timestamp,
    retry_count     number default 0  
);



alter table neoj_apex_export add constraint neoj_apex_export_uk unique  (jobid);



CREATE TABLE neoj_apex_exceptions(    
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jobid NUMBER NOT NULL,
    package_name VARCHAR2(255) NOT NULL,
    procedure_name VARCHAR2(255),
    exception_id VARCHAR2(255),
    err_msg VARCHAR2(3200),
    created_on DATE,
    created_by VARCHAR2(255)
);

-- If you want to make sure that the ID is always populated, even if a value is provided by an insert statement, use the following trigger instead:

CREATE OR REPLACE TRIGGER neoj_apex_exceptions_bir
BEFORE INSERT ON neoj_apex_exceptions
FOR EACH ROW
BEGIN
    :new.created_on:=sysdate;
    :new.created_by:=user;
END;
/



-- =============================================================================
-- Content: APEX TO NEO4J BUTTONS STURCTURE
-- Description: Stores APEX application page buttons with their associated
--              dynamic actions and action details.
-- =============================================================================


CREATE TABLE neoj_apex_buttons (
  jobid               NUMBER         NOT NULL,
  dbname              VARCHAR2(100),
  project_name        VARCHAR2(255),
  workspace           VARCHAR2(255),
  application_id      NUMBER         NOT NULL,
  application_name    VARCHAR2(255),
  page_id             NUMBER         NOT NULL,
  page_name           VARCHAR2(255),
  button_id           VARCHAR2(100)  NOT NULL,
  button_sequence     NUMBER,
  button_name         VARCHAR2(255),
  label               VARCHAR2(4000),
  button_action       VARCHAR2(255),
  button_action_code  VARCHAR2(4000),
  last_updated_by     VARCHAR2(255),
  last_updated_on     DATE,
  CONSTRAINT neoj_apex_buttons_pk
    PRIMARY KEY (jobid, application_id, page_id, button_id)
);

CREATE TABLE neoj_apex_dynamic_actions (
  jobid               NUMBER         NOT NULL,
  dbname              VARCHAR2(100),
  project_name        VARCHAR2(255),
  workspace           VARCHAR2(255),
  application_id      NUMBER         NOT NULL,
  application_name    VARCHAR2(255),
  page_id             NUMBER         NOT NULL,
  page_name           VARCHAR2(255),
  dynamic_action_id   VARCHAR2(100)  NOT NULL,
  dynamic_action_name VARCHAR2(255),
  dynamic_action_seq  NUMBER,
  when_selection_type VARCHAR2(255),
  when_event_name     VARCHAR2(255),
  last_updated_by     VARCHAR2(255),
  last_updated_on     DATE,
  CONSTRAINT neoj_apex_da_pk
    PRIMARY KEY (jobid, application_id, page_id, dynamic_action_id)
);

CREATE TABLE neoj_apex_dynamic_action_acts (
  jobid                        NUMBER         NOT NULL,
  dbname                       VARCHAR2(100),
  project_name                 VARCHAR2(255),
  workspace                    VARCHAR2(255),
  application_id               NUMBER         NOT NULL,
  page_id                      NUMBER         NOT NULL,
  dynamic_action_id            VARCHAR2(100)  NOT NULL,
  action_id                    VARCHAR2(100)  NOT NULL,
  action_name                  VARCHAR2(255),
  action_sequence              NUMBER,
  dynamic_action_event_result  VARCHAR2(255),
  execute_on_page_init         VARCHAR2(10),
  attribute_01                 VARCHAR2(4000),
  attribute_02                 VARCHAR2(4000),
  attribute_03                 VARCHAR2(4000),
  attribute_04                 VARCHAR2(4000),
  attribute_05                 VARCHAR2(4000),
  attribute_06                 VARCHAR2(4000),
  attribute_07                 VARCHAR2(4000),
  attribute_08                 VARCHAR2(4000),
  attribute_09                 VARCHAR2(4000),
  attribute_10                 VARCHAR2(4000),
  attribute_11                 VARCHAR2(4000),
  attribute_12                 VARCHAR2(4000),
  attribute_13                 VARCHAR2(4000),
  attribute_14                 VARCHAR2(4000),
  attribute_15                 VARCHAR2(4000),
  stop_execution_on_error      VARCHAR2(10),
  wait_for_result              VARCHAR2(10),
  last_updated_by              VARCHAR2(255),
  last_updated_on              DATE,
  CONSTRAINT neoj_apex_da_acts_pk
    PRIMARY KEY (jobid, application_id, page_id, dynamic_action_id, action_id)
);

CREATE TABLE neoj_apex_da_act_links (
  jobid               NUMBER         NOT NULL,
  dbname              VARCHAR2(100),
  project_name        VARCHAR2(255),
  workspace           VARCHAR2(255),
  application_id      NUMBER         NOT NULL,
  page_id             NUMBER         NOT NULL,
  dynamic_action_id   VARCHAR2(100)  NOT NULL,
  action_id           VARCHAR2(100)  NOT NULL,
  link_type           VARCHAR2(30)   NOT NULL,
  CONSTRAINT neoj_apex_da_act_links_pk
    PRIMARY KEY (jobid, application_id, page_id, dynamic_action_id, action_id, link_type)
);



CREATE TABLE neoj_apex_page_processes (
  jobid                  NUMBER         NOT NULL,
  dbname                 VARCHAR2(100),
  project_name           VARCHAR2(255),
  workspace              VARCHAR2(255),
  application_id         NUMBER         NOT NULL,
  application_name       VARCHAR2(255),
  page_id                NUMBER         NOT NULL,
  page_name              VARCHAR2(255),
  process_id             VARCHAR2(100)  NOT NULL,
  process_name           VARCHAR2(255),
  execution_sequence     NUMBER,
  process_point          VARCHAR2(255),
  process_point_code     VARCHAR2(255),
  process_type           VARCHAR2(255),
  process_type_code      VARCHAR2(255),
  process_source         CLOB,
  process_source_language VARCHAR2(255),
  condition_type         VARCHAR2(255),
  condition_type_code    VARCHAR2(255),
  condition_expression1  VARCHAR2(4000),
  condition_expression2  VARCHAR2(4000),
  when_button_pressed    VARCHAR2(255),
  when_button_pressed_id VARCHAR2(100),
  region_id              VARCHAR2(100),
  region_name            VARCHAR2(255),
  last_updated_by        VARCHAR2(255),
  last_updated_on        DATE,
  CONSTRAINT neoj_apex_page_proc_pk
    PRIMARY KEY (jobid, application_id, page_id, process_id)
);

CREATE TABLE neoj_apex_button_process_links (
  jobid                  NUMBER         NOT NULL,
  dbname                 VARCHAR2(100),
  project_name           VARCHAR2(255),
  workspace              VARCHAR2(255),
  application_id         NUMBER         NOT NULL,
  page_id                NUMBER         NOT NULL,
  button_id              VARCHAR2(100)  NOT NULL,
  process_id             VARCHAR2(100)  NOT NULL,
  link_type              VARCHAR2(30)   NOT NULL,
  CONSTRAINT neoj_apex_btn_proc_lnk_pk
    PRIMARY KEY (jobid, application_id, page_id, button_id, process_id, link_type)
);

CREATE TABLE neoj_apex_button_da_links (
  jobid               NUMBER         NOT NULL,
  dbname              VARCHAR2(100),
  project_name        VARCHAR2(255),
  workspace           VARCHAR2(255),
  application_id      NUMBER         NOT NULL,
  page_id             NUMBER         NOT NULL,
  button_id           VARCHAR2(100)  NOT NULL,
  dynamic_action_id   VARCHAR2(100)  NOT NULL,
  when_event_name     VARCHAR2(255),
  when_button         VARCHAR2(255),
  link_type           VARCHAR2(30)   NOT NULL,
  CONSTRAINT neoj_apex_btn_da_lnk_pk
    PRIMARY KEY (jobid, application_id, page_id, button_id, dynamic_action_id, link_type)
);



CREATE TABLE neoj_apex_button_act_links (
  jobid               NUMBER         NOT NULL,
  dbname              VARCHAR2(100),
  project_name        VARCHAR2(255),
  workspace           VARCHAR2(255),
  application_id      NUMBER         NOT NULL,
  page_id             NUMBER         NOT NULL,
  button_id           VARCHAR2(100)  NOT NULL,
  dynamic_action_id   VARCHAR2(100)  NOT NULL,
  action_id           VARCHAR2(100)  NOT NULL,
  link_type           VARCHAR2(30)   NOT NULL,
  CONSTRAINT neoj_apex_btn_act_lnk_pk
    PRIMARY KEY (
      jobid,
      application_id,
      page_id,
      button_id,
      dynamic_action_id,
      action_id,
      link_type
    )
);



CREATE INDEX neoj_apex_buttons_i1
  ON neoj_apex_buttons (jobid, application_id, page_id);

CREATE INDEX neoj_apex_da_i1
  ON neoj_apex_dynamic_actions (jobid, application_id, page_id);

CREATE INDEX neoj_apex_da_acts_i1
  ON neoj_apex_dynamic_action_acts (jobid, application_id, page_id, dynamic_action_id);

CREATE INDEX neoj_apex_da_act_links_i1
  ON neoj_apex_da_act_links (jobid, application_id, page_id, dynamic_action_id);

-- =============================================================================
-- Content: APEX TO NEO4J BUTTONS STURCTURE
-- =============================================================================



DECLARE
  l_clob CLOB;
BEGIN
  apex_json.initialize_clob_output;

  apex_json.open_object;
  apex_json.open_array('data');

  FOR rec IN (
    SELECT
      jobid,
      dbName,
      application_id,
      application_name,
      page_id,
      page_name,
      region_id,
      region_name,
      query_type,
      source_type,
      region_source,
      referenced_owner,
      referenced_name,
      referenced_type,
      table_owner,
      table_name
    FROM neoj_apex_structure
    WHERE jobid = :JOBID   -- <=== bind variable in SQL Workshop
    ORDER BY application_id, page_id, region_id
  )
  LOOP
    apex_json.open_object;

    apex_json.write('jobid',           rec.jobid);
    apex_json.write('dbName',          rec.dbName);
    apex_json.write('applicationId',   rec.application_id);
    apex_json.write('applicationName', rec.application_name);
    apex_json.write('pageId',          rec.page_id);
    apex_json.write('pageName',        rec.page_name);
    apex_json.write('regionId',        rec.region_id);
    apex_json.write('regionName',      rec.region_name);
    apex_json.write('queryType',       rec.query_type);
    apex_json.write('sourceType',      rec.source_type);
    apex_json.write('regionSource',    rec.region_source);

    apex_json.write('referencedOwner', rec.referenced_owner);
    apex_json.write('referencedName',  rec.referenced_name);
    apex_json.write('referencedType',  rec.referenced_type);

    apex_json.write('tableOwner',      rec.table_owner);

    apex_json.open_array('tableNames');
    IF rec.table_name IS NOT NULL AND rec.table_name NOT IN ('-', ' ') THEN
      FOR t IN (
        SELECT trim(regexp_substr(rec.table_name, '[^,]+', 1, level)) AS tname
        FROM dual
        CONNECT BY regexp_substr(rec.table_name, '[^,]+', 1, level) IS NOT NULL
      ) LOOP
        apex_json.write(t.tname);
      END LOOP;
    END IF;
    apex_json.close_array;

    apex_json.close_object;
  END LOOP;

  apex_json.close_array; -- data
  apex_json.close_object;

  l_clob := apex_json.get_clob_output;
  apex_json.free_output;

  MERGE INTO neoj_apex_export e
  USING (SELECT :JOBID AS jobid FROM dual) s
  ON (e.jobid = s.jobid)
  WHEN MATCHED THEN
    UPDATE SET e.payload = l_clob, e.created_at = SYSTIMESTAMP
  WHEN NOT MATCHED THEN
    INSERT (jobid, payload) VALUES (:JOBID, l_clob);

END;
/


CREATE TABLE neoj_ora_package_procedure (
    -- Job / context
    jobid               NUMBER          NOT NULL,
    dbname              VARCHAR2(128),
    project_name        VARCHAR2(256),

    -- Source package (where the CALL was found)
    source_owner        VARCHAR2(128),
    source_package      VARCHAR2(128),
    source_procedure    VARCHAR2(128),   -- procedure containing the call
    source_line         NUMBER,          -- line number from ALL_IDENTIFIERS

    -- Called package/procedure
    owner               VARCHAR2(128),
    object_name         VARCHAR2(128),   -- package name
    procedure_name      VARCHAR2(128),   -- procedure/function name

    -- Computed full names
    source_full_name    VARCHAR2(512),   -- dbname.owner.package.procedure
    object_full_name    VARCHAR2(512),   -- dbname.owner.package
    procedure_full_name VARCHAR2(512),   -- dbname.owner.package.procedure

    -- Metadata
    last_updated_by     VARCHAR2(128)    DEFAULT USER,
    last_updated_on     DATE             DEFAULT SYSDATE,
    usage varchar2(255),

    CONSTRAINT pk_neoj_ora_pkg_prc PRIMARY KEY (jobid, source_owner, source_package, source_procedure, owner, object_name, procedure_name)
);

alter table NEOJ_ORA_PACKAGE_PROCEDURE add SIGNATURE varchar2(4000 byte);
alter table NEOJ_ORA_PACKAGE_PROCEDURE add SOURCE_SIGNATURE varchar2(4000 byte);

CREATE INDEX idx_neoj_ora_pkg_prc_job    ON neoj_ora_package_procedure (jobid);
CREATE INDEX idx_neoj_ora_pkg_prc_src    ON neoj_ora_package_procedure (source_owner, source_package);
CREATE INDEX idx_neoj_ora_pkg_prc_called ON neoj_ora_package_procedure (owner, object_name, procedure_name);


create table neoj_ora_package_procedure_crud (
    jobid                number,
    dbname               varchar2(128),
    project_name         varchar2(200),
    package_owner        varchar2(128),
    package_name         varchar2(128),
    procedure_name       varchar2(128),
    proc_start_line      number,
    proc_end_line        number,
    source_line          number,
    table_owner          varchar2(128),
    table_name           varchar2(128),
    ref_type             varchar2(30),
    dml_type             varchar2(30),
    source_text          varchar2(4000),
    package_full_name    varchar2(400),
    procedure_full_name  varchar2(500),
    object_full_name     varchar2(400),
    last_updated_by      varchar2(255),
    last_updated_on      date
);


create unique index neoj_ora_pkg_prc_crud_u1
    on neoj_ora_package_procedure_crud (
        jobid,
        package_owner,
        package_name,
        procedure_name,
        source_line,
        table_owner,
        table_name,
        nvl(dml_type, '?')
    );
    
    
    

CREATE TABLE ME_CODES (CODE_GROUP VARCHAR2(255) NOT NULL, CODE VARCHAR2(255) NOT NULL, CODE_VALUE VARCHAR2(255) NOT NULL);

CREATE UNIQUE INDEX ME_CODES_PK ON ME_CODES(CODE_GROUP, CODE);

/* =========================================================
   ME_LEGACY_APP_STATUS
   ========================================================= */
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ME_LEGACY_APP_STATUS','IDENTIFIED','IDENTIFIED');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ME_LEGACY_APP_STATUS','IN_ANALYSIS','IN_ANALYSIS');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ME_LEGACY_APP_STATUS','IN_SCOPE','IN_SCOPE');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ME_LEGACY_APP_STATUS','PARTIALLY_MIGRATED','PARTIALLY_MIGRATED');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ME_LEGACY_APP_STATUS','MIGRATED','MIGRATED');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ME_LEGACY_APP_STATUS','ON_HOLD','ON_HOLD');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ME_LEGACY_APP_STATUS','OUT_OF_SCOPE','OUT_OF_SCOPE');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ME_LEGACY_APP_STATUS','RETIRED','RETIRED');


/* =========================================================
   ME_MIG_CASE_STATUS
   ========================================================= */
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ME_MIG_CASE_STATUS','DRAFT','DRAFT');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ME_MIG_CASE_STATUS','IDENTIFIED','IDENTIFIED');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ME_MIG_CASE_STATUS','ANALYSING','ANALYSING');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ME_MIG_CASE_STATUS','READY_FOR_DECISION','READY_FOR_DECISION');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ME_MIG_CASE_STATUS','APPROVED','APPROVED');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ME_MIG_CASE_STATUS','IN_IMPLEMENTATION','IN_IMPLEMENTATION');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ME_MIG_CASE_STATUS','IN_TEST','IN_TEST');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ME_MIG_CASE_STATUS','DONE','DONE');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ME_MIG_CASE_STATUS','ON_HOLD','ON_HOLD');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ME_MIG_CASE_STATUS','REJECTED','REJECTED');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ME_MIG_CASE_STATUS','CANCELLED','CANCELLED');


/* =========================================================
   ME_MIG_CASE_DECISION_TYPE
   ========================================================= */
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ME_MIG_CASE_DECISION_TYPE','REBUILD_IN_APEX','REBUILD_IN_APEX');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ME_MIG_CASE_DECISION_TYPE','REPLACE_WITH_STANDARD_APEX','REPLACE_WITH_STANDARD_APEX');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ME_MIG_CASE_DECISION_TYPE','REPLACE_WITH_OTHER_SYSTEM','REPLACE_WITH_OTHER_SYSTEM');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ME_MIG_CASE_DECISION_TYPE','KEEP_AS_IS','KEEP_AS_IS');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ME_MIG_CASE_DECISION_TYPE','DROP','DROP');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ME_MIG_CASE_DECISION_TYPE','POSTPONE','POSTPONE');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ME_MIG_CASE_DECISION_TYPE','UNKNOWN','UNKNOWN');


/* =========================================================
   ORA_BLOCK_MIG_STATUS
   ========================================================= */
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_BLOCK_MIG_STATUS','NOT_ANALYSED','NOT_ANALYSED');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_BLOCK_MIG_STATUS','ANALYSED','ANALYSED');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_BLOCK_MIG_STATUS','MAPPED','MAPPED');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_BLOCK_MIG_STATUS','READY_FOR_BUILD','READY_FOR_BUILD');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_BLOCK_MIG_STATUS','IN_BUILD','IN_BUILD');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_BLOCK_MIG_STATUS','IN_TEST','IN_TEST');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_BLOCK_MIG_STATUS','MIGRATED','MIGRATED');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_BLOCK_MIG_STATUS','PARTIALLY_MIGRATED','PARTIALLY_MIGRATED');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_BLOCK_MIG_STATUS','ON_HOLD','ON_HOLD');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_BLOCK_MIG_STATUS','NOT_IN_SCOPE','NOT_IN_SCOPE');


/* =========================================================
   ORA_BLOCK_MIG_BLOCK_TYPE
   ========================================================= */
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_BLOCK_MIG_BLOCK_TYPE','DATA_BLOCK','DATA_BLOCK');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_BLOCK_MIG_BLOCK_TYPE','CONTROL_BLOCK','CONTROL_BLOCK');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_BLOCK_MIG_BLOCK_TYPE','DISPLAY_BLOCK','DISPLAY_BLOCK');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_BLOCK_MIG_BLOCK_TYPE','PARAMETER_BLOCK','PARAMETER_BLOCK');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_BLOCK_MIG_BLOCK_TYPE','UNKNOWN','UNKNOWN');


/* =========================================================
   ORA_CODE_OBJECT_MIG_STATUS
   ========================================================= */
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_CODE_OBJECT_MIG_STATUS','NOT_ANALYSED','NOT_ANALYSED');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_CODE_OBJECT_MIG_STATUS','ANALYSED','ANALYSED');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_CODE_OBJECT_MIG_STATUS','MAPPED','MAPPED');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_CODE_OBJECT_MIG_STATUS','READY_FOR_BUILD','READY_FOR_BUILD');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_CODE_OBJECT_MIG_STATUS','IN_BUILD','IN_BUILD');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_CODE_OBJECT_MIG_STATUS','IN_TEST','IN_TEST');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_CODE_OBJECT_MIG_STATUS','MIGRATED','MIGRATED');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_CODE_OBJECT_MIG_STATUS','PARTIALLY_MIGRATED','PARTIALLY_MIGRATED');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_CODE_OBJECT_MIG_STATUS','ON_HOLD','ON_HOLD');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_CODE_OBJECT_MIG_STATUS','NOT_IN_SCOPE','NOT_IN_SCOPE');


/* =========================================================
   ORA_CODE_OBJECT_TYPE
   ========================================================= */
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_CODE_OBJECT_TYPE','BUTTON','BUTTON');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_CODE_OBJECT_TYPE','TRIGGER','TRIGGER');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_CODE_OBJECT_TYPE','FORM_PROCEDURE','FORM_PROCEDURE');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_CODE_OBJECT_TYPE','FORM_FUNCTION','FORM_FUNCTION');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_CODE_OBJECT_TYPE','PROGRAM_UNIT','PROGRAM_UNIT');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_CODE_OBJECT_TYPE','MENU_ACTION','MENU_ACTION');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_CODE_OBJECT_TYPE','OTHER','OTHER');


/* =========================================================
   ORA_CODE_OBJECT_SCOPE_TYPE
   ========================================================= */
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_CODE_OBJECT_SCOPE_TYPE','FORM','FORM');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_CODE_OBJECT_SCOPE_TYPE','BLOCK','BLOCK');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_CODE_OBJECT_SCOPE_TYPE','ITEM','ITEM');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_CODE_OBJECT_SCOPE_TYPE','GLOBAL','GLOBAL');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_CODE_OBJECT_SCOPE_TYPE','MENU','MENU');


/* =========================================================
   ORA_FORM_MIG_STATUS
   ========================================================= */
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_FORM_MIG_STATUS','NOT_ANALYSED','NOT_ANALYSED');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_FORM_MIG_STATUS','ANALYSED','ANALYSED');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_FORM_MIG_STATUS','MAPPED','MAPPED');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_FORM_MIG_STATUS','READY_FOR_BUILD','READY_FOR_BUILD');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_FORM_MIG_STATUS','IN_BUILD','IN_BUILD');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_FORM_MIG_STATUS','IN_TEST','IN_TEST');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_FORM_MIG_STATUS','MIGRATED','MIGRATED');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_FORM_MIG_STATUS','PARTIALLY_MIGRATED','PARTIALLY_MIGRATED');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_FORM_MIG_STATUS','ON_HOLD','ON_HOLD');
INSERT INTO ME_CODES (CODE_GROUP, CODE, CODE_VALUE) VALUES ('ORA_FORM_MIG_STATUS','NOT_IN_SCOPE','NOT_IN_SCOPE');



CREATE TABLE NEOJ_APEX_PACKAGE_PROCEDURE
(
  JOBID               NUMBER                    NOT NULL,
  DBNAME              VARCHAR2(256 BYTE),
  PROJECT_NAME        VARCHAR2(255 BYTE),
  WORKSPACE           VARCHAR2(255 BYTE),
  APPLICATION_ID      NUMBER                    NOT NULL,
  APPLICATION_NAME    VARCHAR2(255 BYTE),
  PAGE_ID             NUMBER                    NOT NULL,
  PAGE_NAME           VARCHAR2(255 BYTE),
  BUTTON_ID           VARCHAR2(100 BYTE)        NOT NULL,
  BUTTON_SEQUENCE     NUMBER,
  BUTTON_NAME         VARCHAR2(255 BYTE),
  LABEL               VARCHAR2(4000 BYTE),
  BUTTON_ACTION       VARCHAR2(255 BYTE),
  BUTTON_ACTION_CODE  VARCHAR2(4000 BYTE),
  CODE_TXT            VARCHAR2(4000 BYTE),
  LAST_UPDATED_BY     VARCHAR2(128 BYTE),
  LAST_UPDATED_ON     DATE,
  OWNER               VARCHAR2(128 BYTE),
  OBJECT_NAME         VARCHAR2(128 BYTE),
  PROCEDURE_NAME      VARCHAR2(128 BYTE)
)
;


CREATE TABLE ME_ORA_BLOCK
(
  ORA_BLOCK_ID       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY ( START WITH 21 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP) NOT NULL,
  ORA_FORM_ID        NUMBER                     NOT NULL,
  BLOCK_CODE         VARCHAR2(700 CHAR)         NOT NULL,
  BLOCK_NAME         VARCHAR2(300 CHAR)         NOT NULL,
  BLOCK_TYPE         VARCHAR2(30 CHAR)          NOT NULL,
  DATA_SOURCE_NAME   VARCHAR2(300 CHAR)         NOT NULL,
  IS_DATABASE_BLOCK  VARCHAR2(1 CHAR)           DEFAULT 'N'                   NOT NULL,
  IS_CONTROL_BLOCK   VARCHAR2(1 CHAR)           DEFAULT 'N'                   NOT NULL,
  USAGE_TYPE         VARCHAR2(100 CHAR),
  DESCRIPTION        VARCHAR2(4000 CHAR),
  MIGRATION_STATUS   VARCHAR2(30 CHAR)          NOT NULL,
  NOTES              CLOB,
  CREATED_AT         TIMESTAMP(6)               DEFAULT current_timestamp     NOT NULL,
  CREATED_BY         VARCHAR2(255 CHAR)         DEFAULT coalesce(sys_context('APEX$SESSION','APP_USER'), user) NOT NULL,
  UPDATED_AT         TIMESTAMP(6),
  UPDATED_BY         VARCHAR2(255 CHAR)
)
LOB (NOTES) STORE AS SECUREFILE ;

COMMENT ON TABLE ME_ORA_BLOCK IS 'Evidenca Oracle Forms blockov znotraj forme.';

COMMENT ON COLUMN ME_ORA_BLOCK.ORA_BLOCK_ID IS 'Primarni ključ blocka.';

COMMENT ON COLUMN ME_ORA_BLOCK.ORA_FORM_ID IS 'Sklic na pripadajočo Oracle Forms formo.';

COMMENT ON COLUMN ME_ORA_BLOCK.BLOCK_CODE IS 'Unikatna koda blocka; praviloma sestavljena iz form_code in block_name.';

COMMENT ON COLUMN ME_ORA_BLOCK.BLOCK_NAME IS 'Tehnično ime blocka iz Oracle Forms.';

COMMENT ON COLUMN ME_ORA_BLOCK.BLOCK_TYPE IS 'Tip blocka.';

COMMENT ON COLUMN ME_ORA_BLOCK.DATA_SOURCE_NAME IS 'Ime podatkovnega vira, tabele, viewa ali drugega vira podatkov.';

COMMENT ON COLUMN ME_ORA_BLOCK.IS_DATABASE_BLOCK IS 'Ali je block podatkovni block na bazi (Y/N).';

COMMENT ON COLUMN ME_ORA_BLOCK.IS_CONTROL_BLOCK IS 'Ali je block kontrolni block (Y/N).';

COMMENT ON COLUMN ME_ORA_BLOCK.USAGE_TYPE IS 'Dodatna klasifikacija namena uporabe blocka.';

COMMENT ON COLUMN ME_ORA_BLOCK.DESCRIPTION IS 'Opis blocka.';

COMMENT ON COLUMN ME_ORA_BLOCK.MIGRATION_STATUS IS 'Migracijski status blocka.';

COMMENT ON COLUMN ME_ORA_BLOCK.NOTES IS 'Dodatne opombe.';

COMMENT ON COLUMN ME_ORA_BLOCK.CREATED_AT IS 'Čas kreiranja zapisa.';

COMMENT ON COLUMN ME_ORA_BLOCK.CREATED_BY IS 'Uporabnik, ki je ustvaril zapis.';

COMMENT ON COLUMN ME_ORA_BLOCK.UPDATED_AT IS 'Čas zadnje spremembe zapisa.';

COMMENT ON COLUMN ME_ORA_BLOCK.UPDATED_BY IS 'Uporabnik, ki je nazadnje spremenil zapis.';


CREATE INDEX IX_ME_ORA_BLOCK_FORM ON ME_ORA_BLOCK
(ORA_FORM_ID);

CREATE UNIQUE INDEX PK_ME_ORA_BLOCK ON ME_ORA_BLOCK
(ORA_BLOCK_ID);

CREATE UNIQUE INDEX UK_ME_ORA_BLOCK_01 ON ME_ORA_BLOCK
(BLOCK_CODE);

ALTER TABLE ME_ORA_BLOCK ADD (
  CONSTRAINT CK_ME_ORA_BLOCK_CTRL
  CHECK (is_control_block in ('Y','N'))
  ENABLE VALIDATE,
  CONSTRAINT CK_ME_ORA_BLOCK_DB
  CHECK (is_database_block in ('Y','N'))
  ENABLE VALIDATE,
  CONSTRAINT PK_ME_ORA_BLOCK
  PRIMARY KEY
  (ORA_BLOCK_ID)
  USING INDEX PK_ME_ORA_BLOCK
  ENABLE VALIDATE,
  CONSTRAINT UK_ME_ORA_BLOCK_01
  UNIQUE (BLOCK_CODE)
  USING INDEX UK_ME_ORA_BLOCK_01
  ENABLE VALIDATE);

ALTER TABLE ME_ORA_BLOCK ADD (
  CONSTRAINT FK_ME_ORA_BLOCK_FORM 
  FOREIGN KEY (ORA_FORM_ID) 
  REFERENCES ME_ORA_FORM (ORA_FORM_ID)
  ENABLE VALIDATE);


CREATE TABLE ME_ORA_CODE_OBJECT
(
  ORA_CODE_OBJECT_ID  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY ( START WITH 21 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP) NOT NULL,
  ORA_FORM_ID         NUMBER                    NOT NULL,
  ORA_BLOCK_ID        NUMBER,
  OBJECT_CODE         VARCHAR2(1000 CHAR)       NOT NULL,
  OBJECT_NAME         VARCHAR2(300 CHAR)        NOT NULL,
  OBJECT_TYPE         VARCHAR2(30 CHAR)         NOT NULL,
  SCOPE_TYPE          VARCHAR2(30 CHAR)         NOT NULL,
  TRIGGER_EVENT       VARCHAR2(100 CHAR),
  IS_ENTRY_POINT      VARCHAR2(1 CHAR)          DEFAULT 'N'                   NOT NULL,
  CODE_TEXT           CLOB                      NOT NULL,
  DESCRIPTION         VARCHAR2(4000 CHAR),
  MIGRATION_STATUS    VARCHAR2(30 CHAR),
  NOTES               CLOB,
  CREATED_AT          TIMESTAMP(6)              DEFAULT current_timestamp     NOT NULL,
  CREATED_BY          VARCHAR2(255 CHAR)        DEFAULT coalesce(sys_context('APEX$SESSION','APP_USER'), user) NOT NULL,
  UPDATED_AT          TIMESTAMP(6),
  UPDATED_BY          VARCHAR2(255 CHAR)
)
LOB (CODE_TEXT) STORE AS SECUREFILE 
LOB (NOTES) STORE AS SECUREFILE ;

COMMENT ON TABLE ME_ORA_CODE_OBJECT IS 'Generični legacy izvršilni ali dogodkovni objekt, kot so gumbi, triggerji, procedure in podobno.';

COMMENT ON COLUMN ME_ORA_CODE_OBJECT.ORA_CODE_OBJECT_ID IS 'Primarni ključ code objekta.';

COMMENT ON COLUMN ME_ORA_CODE_OBJECT.ORA_FORM_ID IS 'Obvezen sklic na Oracle Forms formo.';

COMMENT ON COLUMN ME_ORA_CODE_OBJECT.ORA_BLOCK_ID IS 'Opcijski sklic na block, če je objekt vezan na konkreten block.';

COMMENT ON COLUMN ME_ORA_CODE_OBJECT.OBJECT_CODE IS 'Unikatna koda objekta; praviloma sestavljen identifikator iz block_code oziroma form_code in object_name.';

COMMENT ON COLUMN ME_ORA_CODE_OBJECT.OBJECT_NAME IS 'Tehnično ime objekta.';

COMMENT ON COLUMN ME_ORA_CODE_OBJECT.OBJECT_TYPE IS 'Tip code objekta.';

COMMENT ON COLUMN ME_ORA_CODE_OBJECT.SCOPE_TYPE IS 'Nivo dosega objekta, npr. FORM, BLOCK ali GLOBAL.';

COMMENT ON COLUMN ME_ORA_CODE_OBJECT.TRIGGER_EVENT IS 'Dogodek triggerja, če gre za trigger.';

COMMENT ON COLUMN ME_ORA_CODE_OBJECT.IS_ENTRY_POINT IS 'Oznaka, ali je objekt vstopna točka uporabniške ali sistemske logike (Y/N).';

COMMENT ON COLUMN ME_ORA_CODE_OBJECT.CODE_TEXT IS 'Izvorno besedilo PL/SQL ali trigger logike.';

COMMENT ON COLUMN ME_ORA_CODE_OBJECT.DESCRIPTION IS 'Opis objekta.';

COMMENT ON COLUMN ME_ORA_CODE_OBJECT.MIGRATION_STATUS IS 'Migracijski status code objekta.';

COMMENT ON COLUMN ME_ORA_CODE_OBJECT.NOTES IS 'Dodatne opombe.';

COMMENT ON COLUMN ME_ORA_CODE_OBJECT.CREATED_AT IS 'Čas kreiranja zapisa.';

COMMENT ON COLUMN ME_ORA_CODE_OBJECT.CREATED_BY IS 'Uporabnik, ki je ustvaril zapis.';

COMMENT ON COLUMN ME_ORA_CODE_OBJECT.UPDATED_AT IS 'Čas zadnje spremembe zapisa.';

COMMENT ON COLUMN ME_ORA_CODE_OBJECT.UPDATED_BY IS 'Uporabnik, ki je nazadnje spremenil zapis.';


CREATE INDEX IX_ME_ORA_CODE_OBJ_BLOCK ON ME_ORA_CODE_OBJECT
(ORA_BLOCK_ID);

CREATE INDEX IX_ME_ORA_CODE_OBJ_FORM ON ME_ORA_CODE_OBJECT
(ORA_FORM_ID);

CREATE UNIQUE INDEX PK_ME_ORA_CODE_OBJECT ON ME_ORA_CODE_OBJECT
(ORA_CODE_OBJECT_ID);

CREATE UNIQUE INDEX UK_ME_ORA_CODE_OBJECT_01 ON ME_ORA_CODE_OBJECT
(OBJECT_CODE, TRIGGER_EVENT);

ALTER TABLE ME_ORA_CODE_OBJECT ADD (
  CONSTRAINT CK_ME_ORA_CODE_ENTRY
  CHECK (is_entry_point in ('Y','N'))
  ENABLE VALIDATE,
  CONSTRAINT PK_ME_ORA_CODE_OBJECT
  PRIMARY KEY
  (ORA_CODE_OBJECT_ID)
  USING INDEX PK_ME_ORA_CODE_OBJECT
  ENABLE VALIDATE,
  CONSTRAINT UK_ME_ORA_CODE_OBJECT_01
  UNIQUE (OBJECT_CODE, TRIGGER_EVENT)
  USING INDEX UK_ME_ORA_CODE_OBJECT_01
  ENABLE VALIDATE);

ALTER TABLE ME_ORA_CODE_OBJECT ADD (
  CONSTRAINT FK_ME_ORA_CODE_OBJ_BLOCK 
  FOREIGN KEY (ORA_BLOCK_ID) 
  REFERENCES ME_ORA_BLOCK (ORA_BLOCK_ID)
  ENABLE VALIDATE,
  CONSTRAINT FK_ME_ORA_CODE_OBJ_FORM 
  FOREIGN KEY (ORA_FORM_ID) 
  REFERENCES ME_ORA_FORM (ORA_FORM_ID)
  ENABLE VALIDATE);


CREATE TABLE ME_ORA_FORM
(
  ORA_FORM_ID       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY ( START WITH 21 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP) NOT NULL,
  LEGACY_APP_ID     NUMBER                      NOT NULL,
  FORM_CODE         VARCHAR2(500 CHAR)          NOT NULL,
  FORM_NAME         VARCHAR2(300 CHAR)          NOT NULL,
  MODULE_NAME       VARCHAR2(300 CHAR)          NOT NULL,
  FILE_NAME         VARCHAR2(300 CHAR),
  FILE_PATH         VARCHAR2(1000 CHAR),
  DESCRIPTION       VARCHAR2(4000 CHAR),
  BUSINESS_PURPOSE  VARCHAR2(1000 CHAR)         NOT NULL,
  MIGRATION_STATUS  VARCHAR2(30 CHAR)           NOT NULL,
  NOTES             CLOB,
  CREATED_AT        TIMESTAMP(6)                DEFAULT current_timestamp     NOT NULL,
  CREATED_BY        VARCHAR2(255 CHAR)          DEFAULT coalesce(sys_context('APEX$SESSION','APP_USER'), user) NOT NULL,
  UPDATED_AT        TIMESTAMP(6),
  UPDATED_BY        VARCHAR2(255 CHAR)
)
LOB (NOTES) STORE AS SECUREFILE;

COMMENT ON TABLE ME_ORA_FORM IS 'Evidenca Oracle Forms form, ki sodelujejo v migraciji.';

COMMENT ON COLUMN ME_ORA_FORM.ORA_FORM_ID IS 'Primarni ključ forme.';

COMMENT ON COLUMN ME_ORA_FORM.LEGACY_APP_ID IS 'Sklic na pripadajočo legacy aplikacijo.';

COMMENT ON COLUMN ME_ORA_FORM.FORM_CODE IS 'Unikatna koda forme; praviloma pot do forme v menuju ali drug stabilen identifikator.';

COMMENT ON COLUMN ME_ORA_FORM.FORM_NAME IS 'Uporabniško razumljiv naziv forme.';

COMMENT ON COLUMN ME_ORA_FORM.MODULE_NAME IS 'Tehnično ime Oracle Forms modula.';

COMMENT ON COLUMN ME_ORA_FORM.FILE_NAME IS 'Ime izvorne datoteke forme.';

COMMENT ON COLUMN ME_ORA_FORM.FILE_PATH IS 'Pot do izvorne datoteke forme.';

COMMENT ON COLUMN ME_ORA_FORM.DESCRIPTION IS 'Opis forme.';

COMMENT ON COLUMN ME_ORA_FORM.BUSINESS_PURPOSE IS 'Poslovni namen forme.';

COMMENT ON COLUMN ME_ORA_FORM.MIGRATION_STATUS IS 'Migracijski status forme.';

COMMENT ON COLUMN ME_ORA_FORM.NOTES IS 'Dodatne opombe.';

COMMENT ON COLUMN ME_ORA_FORM.CREATED_AT IS 'Čas kreiranja zapisa.';

COMMENT ON COLUMN ME_ORA_FORM.CREATED_BY IS 'Uporabnik, ki je ustvaril zapis.';

COMMENT ON COLUMN ME_ORA_FORM.UPDATED_AT IS 'Čas zadnje spremembe zapisa.';

COMMENT ON COLUMN ME_ORA_FORM.UPDATED_BY IS 'Uporabnik, ki je nazadnje spremenil zapis.';


CREATE INDEX IX_ME_ORA_FORM_APP ON ME_ORA_FORM
(LEGACY_APP_ID);

CREATE UNIQUE INDEX PK_ME_ORA_FORM ON ME_ORA_FORM
(ORA_FORM_ID);

CREATE UNIQUE INDEX UK_ME_ORA_FORM_01 ON ME_ORA_FORM
(FORM_CODE);

ALTER TABLE ME_ORA_FORM ADD (
  CONSTRAINT PK_ME_ORA_FORM
  PRIMARY KEY
  (ORA_FORM_ID)
  USING INDEX PK_ME_ORA_FORM
  ENABLE VALIDATE,
  CONSTRAINT UK_ME_ORA_FORM_01
  UNIQUE (FORM_CODE)
  USING INDEX UK_ME_ORA_FORM_01
  ENABLE VALIDATE);

ALTER TABLE ME_ORA_FORM ADD (
  CONSTRAINT FK_ME_ORA_FORM_APP 
  FOREIGN KEY (LEGACY_APP_ID) 
  REFERENCES ME_LEGACY_APPLICATION (LEGACY_APP_ID)
  ENABLE VALIDATE);
