CREATE TABLE TABLE_DUMMY
(
  ID              VARCHAR2(255 BYTE),
  PACKAGE_NAME    VARCHAR2(255 BYTE),
  PROCEDURE_NAME  VARCHAR2(255 BYTE),
  CREATED_ON      DATE,
  CREATED_BY      VARCHAR2(255 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
