
-- Generated by ORDS REST Data Services 25.4.0.r3641739
-- Schema: Y055490  Date: Thu Apr 02 02:26:11 2026 
--
        
DECLARE
  l_roles     OWA.VC_ARR;
  l_modules   OWA.VC_ARR;
  l_patterns  OWA.VC_ARR;

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'ws_cmrlecr',
      p_auto_rest_auth      => FALSE);

  ORDS.DEFINE_MODULE(
      p_module_name    => 'apex-structure',
      p_base_path      => '/apex-structure/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'apex-structure',
      p_pattern        => 'export/{jobid}',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'apex-structure',
      p_pattern        => 'export/{jobid}',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    l_clob CLOB;
BEGIN
    SELECT payload
    INTO l_clob
    FROM neoj_apex_export
    WHERE jobid = :jobid;

    -- HTTP headers
    owa_util.mime_header(''application/json'', FALSE);
    htp.p(''Cache-Control: no-cache'');
    owa_util.http_header_close;

    -- send JSON
    htp.p(l_clob);

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        owa_util.status_line(404, ''Not Found'');
END;');


COMMIT;

END;
/


/*

DECLARE
  v_exported_script CLOB;
BEGIN
  v_exported_script := ORDS_EXPORT.EXPORT_MODULE(
    p_module_name => 'apex-structure'
  );
  dbms_output.put_line(dbms_lob.substr(v_exported_script, 32000, 1));
END;
/
*/