prompt --application/set_environment
set define off verify off feedback off
whenever sqlerror exit sql.sqlcode rollback
--------------------------------------------------------------------------------
--
-- Oracle APEX export file
--
-- You should run this script using a SQL client connected to the database as
-- the owner (parsing schema) of the application or as a database user with the
-- APEX_ADMINISTRATOR_ROLE role.
--
-- This export file has been automatically generated. Modifying this file is not
-- supported by Oracle and can lead to unexpected application and/or instance
-- behavior now or in the future.
--
-- NOTE: Calls to apex_application_install override the defaults below.
--
--------------------------------------------------------------------------------
begin
wwv_flow_imp.import_begin (
 p_version_yyyy_mm_dd=>'2024.11.30'
,p_release=>'24.2.13'
,p_default_workspace_id=>64215835499680511
,p_default_application_id=>117
,p_default_id_offset=>4813894482225087
,p_default_owner=>'Y055490'
);
end;
/
 
prompt APPLICATION 117 - GeneratedApp
--
-- Application Export:
--   Application:     117
--   Name:            GeneratedApp
--   Exported By:     CMRLECR
--   Flashback:       0
--   Export Type:     Page Export
--   Manifest
--     PAGE: 5
--   Manifest End
--   Version:         24.2.13
--   Instance ID:     61906624151536
--

begin
null;
end;
/
prompt --application/pages/delete_00300
begin
wwv_flow_imp_page.remove_page (p_flow_id=>wwv_flow.g_flow_id, p_page_id=>300);
end;
/
prompt --application/pages/page_00300
begin
wwv_flow_imp_page.create_page(
 p_id=>300
,p_name=>'TEST_FORM'
,p_alias=>'TEST_FORM'
,p_step_title=>'TEST_FORM'
,p_autocomplete_on_off=>'OFF'
,p_page_template_options=>'#DEFAULT#'
,p_protection_level=>'C'
,p_page_component_map=>'11'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(90000000000000010)
,p_plug_name=>'Breadcrumb'
,p_region_template_options=>'#DEFAULT#:t-BreadcrumbRegion--useBreadcrumbTitle'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>2531463326621247859
,p_plug_display_sequence=>10
,p_plug_display_point=>'REGION_POSITION_01'
,p_menu_id=>wwv_flow_imp.id(79398070345812936)
,p_plug_source_type=>'NATIVE_BREADCRUMB'
,p_menu_template_id=>4072363345357175094
);

-- ###REGION_DB_BLOCKS_START###
-- Generated classic reports from ME_ORA_BLOCK for ORA_FORM_ID=81 at 2026-04-22 10:02:20
-- Form: TEST_FORM / TEST_FORM
-- Default owner: Y055490
wwv_flow_imp_page.create_report_region(
 p_id=>wwv_flow_imp.id(90000000000000020)
,p_name=>'ME_ORA_FORM'
,p_title=>'Me Ora Form'
,p_template=>null
,p_display_sequence=>20
,p_region_template_options=>'#DEFAULT#'
,p_component_template_options=>'#DEFAULT#'
,p_display_point=>'BODY'
,p_source_type=>'NATIVE_SQL_REPORT'
,p_query_type=>'SQL'
,p_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'select',
'    ORA_FORM_ID,',
'    LEGACY_APP_ID,',
'    FORM_CODE,',
'    FORM_NAME,',
'    MODULE_NAME,',
'    FILE_NAME,',
'    FILE_PATH,',
'    DESCRIPTION,',
'    BUSINESS_PURPOSE,',
'    MIGRATION_STATUS,',
'    CREATED_AT,',
'    CREATED_BY,',
'    UPDATED_AT,',
'    UPDATED_BY',
'from Y055490.ME_ORA_FORM'
))
,p_ajax_enabled=>'Y'
,p_query_row_template=>null
,p_query_num_rows=>15
,p_query_options=>'DERIVED_REPORT_COLUMNS'
,p_query_no_data_found=>'No data found.'
,p_query_num_rows_type=>'NEXT_PREVIOUS_LINKS'
,p_pagination_display_position=>'BOTTOM_RIGHT'
,p_csv_output=>'Y'
);

wwv_flow_imp_page.create_report_region(
 p_id=>wwv_flow_imp.id(90000000000000030)
,p_name=>'ME_ORA_BLOCK'
,p_title=>'Me Ora Block'
,p_template=>null
,p_display_sequence=>30
,p_region_template_options=>'#DEFAULT#'
,p_component_template_options=>'#DEFAULT#'
,p_display_point=>'BODY'
,p_source_type=>'NATIVE_SQL_REPORT'
,p_query_type=>'SQL'
,p_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'select',
'    ORA_BLOCK_ID,',
'    ORA_FORM_ID,',
'    BLOCK_CODE,',
'    BLOCK_NAME,',
'    BLOCK_TYPE,',
'    DATA_SOURCE_NAME,',
'    IS_DATABASE_BLOCK,',
'    IS_CONTROL_BLOCK,',
'    USAGE_TYPE,',
'    DESCRIPTION,',
'    MIGRATION_STATUS,',
'    CREATED_AT,',
'    CREATED_BY,',
'    UPDATED_AT,',
'    UPDATED_BY',
'from Y055490.ME_ORA_BLOCK'
))
,p_ajax_enabled=>'Y'
,p_query_row_template=>null
,p_query_num_rows=>15
,p_query_options=>'DERIVED_REPORT_COLUMNS'
,p_query_no_data_found=>'No data found.'
,p_query_num_rows_type=>'NEXT_PREVIOUS_LINKS'
,p_pagination_display_position=>'BOTTOM_RIGHT'
,p_csv_output=>'Y'
);
-- ###REGION_DB_BLOCKS_END###

end;
/
prompt --application/end_environment
begin
-- ###REGION_BUTTONS_START###
-- No buttons/processes generated by apex_genExp_ClassRep.py.
-- ###REGION_BUTTONS_END###


wwv_flow_imp.import_end(p_auto_install_sup_obj => nvl(wwv_flow_application_install.get_auto_install_sup_obj, false)
);
commit;
end;
/
set verify on feedback on define on
prompt  ...done
