prompt --application/set_environment
set define off verify off feedback off
whenever sqlerror exit sql.sqlcode rollback
--------------------------------------------------------------------------------
--
-- APEX page export generated by apex_gen_byExp.py
-- Form:      VMESNIKI_POZAVAROVANJE
-- Generated: 11:31 Tuesday April 21, 2026
--
--------------------------------------------------------------------------------
begin
 wwv_flow_imp.import_begin (
  p_version_yyyy_mm_dd=>'2024.11.30'
 ,p_release=>'24.2.13'
 ,p_default_workspace_id=>64215835499680511
 ,p_default_application_id=>117
 ,p_default_id_offset=>0
 ,p_default_owner=>'Y055490'
 );
end;
/

begin
null;
end;
/

prompt --application/pages/delete_00200
begin
wwv_flow_imp_page.remove_page (p_flow_id=>wwv_flow.g_flow_id, p_page_id=>200);
end;
/

prompt --application/pages/page_00200
begin
wwv_flow_imp_page.create_page(
 p_id=>200
,p_name=>'VMESNIKI_POZAVAROVANJE'
,p_alias=>'VMESNIKIPOZAVAROVANJE'
,p_step_title=>'VMESNIKI_POZAVAROVANJE'
,p_autocomplete_on_off=>'OFF'
,p_page_template_options=>'#DEFAULT#'
,p_protection_level=>'C'
,p_page_component_map=>'21'
);
end;
/

-- === FIXED REGION FRAGMENTS (from f109 template) ===
begin
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(200010)
,p_plug_name=>'Breadcrumb'
,p_region_template_options=>'#DEFAULT#:t-BreadcrumbRegion--useBreadcrumbTitle'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(1437766313018171158)
,p_plug_display_sequence=>10
,p_plug_display_point=>'REGION_POSITION_01'
,p_menu_id=>wwv_flow_imp.id(1437705228138171072)
,p_plug_source_type=>'NATIVE_BREADCRUMB'
,p_menu_template_id=>wwv_flow_imp.id(1437824101496171207)
);
end;
/

begin
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(200020)
,p_plug_name=>'Kriteriji'
,p_region_template_options=>'#DEFAULT#:t-Region--scrollBody'
,p_plug_template=>wwv_flow_imp.id(1437756908475171153)
,p_plug_display_sequence=>40
,p_location=>null
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'expand_shortcuts', 'N',
  'output_as', 'HTML')).to_clob
);
end;
/

begin
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(200030)
,p_plug_name=>'Tabs'
,p_region_template_options=>'#DEFAULT#:t-Region--scrollBody'
,p_plug_template=>wwv_flow_imp.id(1437756908475171153)
,p_plug_display_sequence=>50
,p_include_in_reg_disp_sel_yn=>'Y'
,p_location=>null
,p_plug_source_type=>'NATIVE_DISPLAY_SELECTOR'
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'display_region_icons', 'N',
  'include_show_all', 'Y',
  'rds_mode', 'STANDARD',
  'remember_selection', 'USER')).to_clob
);
end;
/

-- === GENERATED DB BLOCK REGIONS ===
-- DB block: B2 -> VMESNIK_POZAVAROVANJE
begin
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(200050)
,p_plug_name=>'B2'
,p_title=>'B2'
,p_parent_plug_id=>wwv_flow_imp.id(200030)
,p_region_template_options=>'#DEFAULT#'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(1437755083773171151)
,p_plug_display_sequence=>10
,p_include_in_reg_disp_sel_yn=>'Y'
,p_plug_display_point=>'SUB_REGIONS'
,p_query_type=>'SQL'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'select * from VMESNIK_POZAVAROVANJE'
))
,p_plug_source_type=>'NATIVE_IG'
,p_prn_content_disposition=>'ATTACHMENT'
,p_prn_units=>'INCHES'
,p_prn_paper_size=>'LETTER'
,p_prn_width=>11
,p_prn_height=>8.5
,p_prn_orientation=>'HORIZONTAL'
,p_prn_page_header=>'B2'
,p_prn_page_header_font_color=>'#000000'
,p_prn_page_header_font_family=>'Helvetica'
,p_prn_page_header_font_weight=>'normal'
,p_prn_page_header_font_size=>'12'
,p_prn_page_footer_font_color=>'#000000'
,p_prn_page_footer_font_family=>'Helvetica'
,p_prn_page_footer_font_weight=>'normal'
,p_prn_page_footer_font_size=>'12'
,p_prn_header_bg_color=>'#EEEEEE'
,p_prn_header_font_color=>'#000000'
,p_prn_header_font_family=>'Helvetica'
,p_prn_header_font_weight=>'bold'
,p_prn_header_font_size=>'10'
,p_prn_body_bg_color=>'#FFFFFF'
,p_prn_body_font_color=>'#000000'
,p_prn_body_font_family=>'Helvetica'
,p_prn_body_font_weight=>'normal'
,p_prn_body_font_size=>'10'
,p_prn_border_width=>.5
,p_prn_page_header_alignment=>'CENTER'
,p_prn_page_footer_alignment=>'CENTER'
,p_prn_border_color=>'#666666'
);
end;
/

-- DB block: B3 -> VMESNIK_SKODE
begin
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(200070)
,p_plug_name=>'B3'
,p_title=>'B3'
,p_parent_plug_id=>wwv_flow_imp.id(200030)
,p_region_template_options=>'#DEFAULT#'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(1437755083773171151)
,p_plug_display_sequence=>20
,p_include_in_reg_disp_sel_yn=>'Y'
,p_plug_display_point=>'SUB_REGIONS'
,p_query_type=>'SQL'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'select * from VMESNIK_SKODE'
))
,p_plug_source_type=>'NATIVE_IG'
,p_prn_content_disposition=>'ATTACHMENT'
,p_prn_units=>'INCHES'
,p_prn_paper_size=>'LETTER'
,p_prn_width=>11
,p_prn_height=>8.5
,p_prn_orientation=>'HORIZONTAL'
,p_prn_page_header=>'B3'
,p_prn_page_header_font_color=>'#000000'
,p_prn_page_header_font_family=>'Helvetica'
,p_prn_page_header_font_weight=>'normal'
,p_prn_page_header_font_size=>'12'
,p_prn_page_footer_font_color=>'#000000'
,p_prn_page_footer_font_family=>'Helvetica'
,p_prn_page_footer_font_weight=>'normal'
,p_prn_page_footer_font_size=>'12'
,p_prn_header_bg_color=>'#EEEEEE'
,p_prn_header_font_color=>'#000000'
,p_prn_header_font_family=>'Helvetica'
,p_prn_header_font_weight=>'bold'
,p_prn_header_font_size=>'10'
,p_prn_body_bg_color=>'#FFFFFF'
,p_prn_body_font_color=>'#000000'
,p_prn_body_font_family=>'Helvetica'
,p_prn_body_font_weight=>'normal'
,p_prn_body_font_size=>'10'
,p_prn_border_width=>.5
,p_prn_page_header_alignment=>'CENTER'
,p_prn_page_footer_alignment=>'CENTER'
,p_prn_border_color=>'#666666'
);
end;
/

-- DB block: B4 -> VMESNIK_SKODE_TRANSAKCIJE
begin
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(200090)
,p_plug_name=>'B4'
,p_title=>'B4'
,p_parent_plug_id=>wwv_flow_imp.id(200030)
,p_region_template_options=>'#DEFAULT#'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(1437755083773171151)
,p_plug_display_sequence=>30
,p_include_in_reg_disp_sel_yn=>'Y'
,p_plug_display_point=>'SUB_REGIONS'
,p_query_type=>'SQL'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'select * from VMESNIK_SKODE_TRANSAKCIJE'
))
,p_plug_source_type=>'NATIVE_IG'
,p_prn_content_disposition=>'ATTACHMENT'
,p_prn_units=>'INCHES'
,p_prn_paper_size=>'LETTER'
,p_prn_width=>11
,p_prn_height=>8.5
,p_prn_orientation=>'HORIZONTAL'
,p_prn_page_header=>'B4'
,p_prn_page_header_font_color=>'#000000'
,p_prn_page_header_font_family=>'Helvetica'
,p_prn_page_header_font_weight=>'normal'
,p_prn_page_header_font_size=>'12'
,p_prn_page_footer_font_color=>'#000000'
,p_prn_page_footer_font_family=>'Helvetica'
,p_prn_page_footer_font_weight=>'normal'
,p_prn_page_footer_font_size=>'12'
,p_prn_header_bg_color=>'#EEEEEE'
,p_prn_header_font_color=>'#000000'
,p_prn_header_font_family=>'Helvetica'
,p_prn_header_font_weight=>'bold'
,p_prn_header_font_size=>'10'
,p_prn_body_bg_color=>'#FFFFFF'
,p_prn_body_font_color=>'#000000'
,p_prn_body_font_family=>'Helvetica'
,p_prn_body_font_weight=>'normal'
,p_prn_body_font_size=>'10'
,p_prn_border_width=>.5
,p_prn_page_header_alignment=>'CENTER'
,p_prn_page_footer_alignment=>'CENTER'
,p_prn_border_color=>'#666666'
);
end;
/

-- DB block: B5 -> VMESNIK_ZAVAROVANI_OBJEKTI
begin
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(200110)
,p_plug_name=>'B5'
,p_title=>'B5'
,p_parent_plug_id=>wwv_flow_imp.id(200030)
,p_region_template_options=>'#DEFAULT#'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(1437755083773171151)
,p_plug_display_sequence=>40
,p_include_in_reg_disp_sel_yn=>'Y'
,p_plug_display_point=>'SUB_REGIONS'
,p_query_type=>'SQL'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'select * from VMESNIK_ZAVAROVANI_OBJEKTI'
))
,p_plug_source_type=>'NATIVE_IG'
,p_prn_content_disposition=>'ATTACHMENT'
,p_prn_units=>'INCHES'
,p_prn_paper_size=>'LETTER'
,p_prn_width=>11
,p_prn_height=>8.5
,p_prn_orientation=>'HORIZONTAL'
,p_prn_page_header=>'B5'
,p_prn_page_header_font_color=>'#000000'
,p_prn_page_header_font_family=>'Helvetica'
,p_prn_page_header_font_weight=>'normal'
,p_prn_page_header_font_size=>'12'
,p_prn_page_footer_font_color=>'#000000'
,p_prn_page_footer_font_family=>'Helvetica'
,p_prn_page_footer_font_weight=>'normal'
,p_prn_page_footer_font_size=>'12'
,p_prn_header_bg_color=>'#EEEEEE'
,p_prn_header_font_color=>'#000000'
,p_prn_header_font_family=>'Helvetica'
,p_prn_header_font_weight=>'bold'
,p_prn_header_font_size=>'10'
,p_prn_body_bg_color=>'#FFFFFF'
,p_prn_body_font_color=>'#000000'
,p_prn_body_font_family=>'Helvetica'
,p_prn_body_font_weight=>'normal'
,p_prn_body_font_size=>'10'
,p_prn_border_width=>.5
,p_prn_page_header_alignment=>'CENTER'
,p_prn_page_footer_alignment=>'CENTER'
,p_prn_border_color=>'#666666'
);
end;
/

-- === BUTTONS REGION ===
begin
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(200040)
,p_plug_name=>'ButtonsRegion'
,p_region_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(1437732803722171135)
,p_plug_display_sequence=>30
,p_location=>null
,p_plug_header=>wwv_flow_string.join(wwv_flow_t_varchar2(
'Actions',
''))
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'expand_shortcuts', 'N',
  'output_as', 'HTML')).to_clob
);
end;
/

begin
wwv_flow_imp_page.create_page_button(
 p_id=>wwv_flow_imp.id(200130)
,p_button_sequence=>10
,p_button_plug_id=>wwv_flow_imp.id(200040)
,p_button_name=>'POLNJENJE_VMESNIKOV'
,p_button_static_id=>'Page200.ButtonsRegion.POLNJENJE_VMESNIKOV'
,p_button_action=>'SUBMIT'
,p_button_template_options=>'#DEFAULT#'
,p_button_template_id=>wwv_flow_imp.id(1437822766392171206)
,p_button_image_alt=>'Polnjenje Vmesnikov'
,p_grid_new_row=>'N'
,p_grid_new_column=>'Y'
,p_grid_column_span=>1
);
end;
/

begin
wwv_flow_imp_page.create_page_button(
 p_id=>wwv_flow_imp.id(200150)
,p_button_sequence=>20
,p_button_plug_id=>wwv_flow_imp.id(200040)
,p_button_name=>'POLNI_SKODE'
,p_button_static_id=>'Page200.ButtonsRegion.POLNI_SKODE'
,p_button_action=>'SUBMIT'
,p_button_template_options=>'#DEFAULT#'
,p_button_template_id=>wwv_flow_imp.id(1437822766392171206)
,p_button_image_alt=>'Polni Skode'
,p_grid_new_row=>'N'
,p_grid_new_column=>'Y'
,p_grid_column_span=>1
);
end;
/

begin
wwv_flow_imp_page.create_page_button(
 p_id=>wwv_flow_imp.id(200170)
,p_button_sequence=>30
,p_button_plug_id=>wwv_flow_imp.id(200040)
,p_button_name=>'OBDELAVA_BORDEROJEV'
,p_button_static_id=>'Page200.ButtonsRegion.OBDELAVA_BORDEROJEV'
,p_button_action=>'SUBMIT'
,p_button_template_options=>'#DEFAULT#'
,p_button_template_id=>wwv_flow_imp.id(1437822766392171206)
,p_button_image_alt=>'Obdelava Borderojev'
,p_grid_new_row=>'N'
,p_grid_new_column=>'Y'
,p_grid_column_span=>1
);
end;
/

begin
wwv_flow_imp_page.create_page_button(
 p_id=>wwv_flow_imp.id(200190)
,p_button_sequence=>40
,p_button_plug_id=>wwv_flow_imp.id(200040)
,p_button_name=>'OBDELAVA_VMESNIKOV'
,p_button_static_id=>'Page200.ButtonsRegion.OBDELAVA_VMESNIKOV'
,p_button_action=>'SUBMIT'
,p_button_template_options=>'#DEFAULT#'
,p_button_template_id=>wwv_flow_imp.id(1437822766392171206)
,p_button_image_alt=>'Obdelava Vmesnikov'
,p_grid_new_row=>'N'
,p_grid_new_column=>'Y'
,p_grid_column_span=>1
);
end;
/

begin
wwv_flow_imp_page.create_page_button(
 p_id=>wwv_flow_imp.id(200210)
,p_button_sequence=>50
,p_button_plug_id=>wwv_flow_imp.id(200040)
,p_button_name=>'OBDELAVA_FAKTUR'
,p_button_static_id=>'Page200.ButtonsRegion.OBDELAVA_FAKTUR'
,p_button_action=>'SUBMIT'
,p_button_template_options=>'#DEFAULT#'
,p_button_template_id=>wwv_flow_imp.id(1437822766392171206)
,p_button_image_alt=>'Obdelava Faktur'
,p_grid_new_row=>'N'
,p_grid_new_column=>'Y'
,p_grid_column_span=>1
);
end;
/

begin
wwv_flow_imp_page.create_page_button(
 p_id=>wwv_flow_imp.id(200230)
,p_button_sequence=>60
,p_button_plug_id=>wwv_flow_imp.id(200040)
,p_button_name=>'OBDELAVA_SKOD'
,p_button_static_id=>'Page200.ButtonsRegion.OBDELAVA_SKOD'
,p_button_action=>'SUBMIT'
,p_button_template_options=>'#DEFAULT#'
,p_button_template_id=>wwv_flow_imp.id(1437822766392171206)
,p_button_image_alt=>'Obdelava Skod'
,p_grid_new_row=>'N'
,p_grid_new_column=>'Y'
,p_grid_column_span=>1
);
end;
/

begin
wwv_flow_imp_page.create_page_button(
 p_id=>wwv_flow_imp.id(200250)
,p_button_sequence=>70
,p_button_plug_id=>wwv_flow_imp.id(200040)
,p_button_name=>'KONTROLA_SKADENCE'
,p_button_static_id=>'Page200.ButtonsRegion.KONTROLA_SKADENCE'
,p_button_action=>'SUBMIT'
,p_button_template_options=>'#DEFAULT#'
,p_button_template_id=>wwv_flow_imp.id(1437822766392171206)
,p_button_image_alt=>'Kontrola Skadence'
,p_grid_new_row=>'N'
,p_grid_new_column=>'Y'
,p_grid_column_span=>1
);
end;
/

begin
wwv_flow_imp_page.create_page_button(
 p_id=>wwv_flow_imp.id(200270)
,p_button_sequence=>80
,p_button_plug_id=>wwv_flow_imp.id(200040)
,p_button_name=>'NE_OBDELANO'
,p_button_static_id=>'Page200.ButtonsRegion.NE_OBDELANO'
,p_button_action=>'SUBMIT'
,p_button_template_options=>'#DEFAULT#'
,p_button_template_id=>wwv_flow_imp.id(1437822766392171206)
,p_button_image_alt=>'Ne Obdelano'
,p_grid_new_row=>'N'
,p_grid_new_column=>'Y'
,p_grid_column_span=>1
);
end;
/

begin
wwv_flow_imp_page.create_page_button(
 p_id=>wwv_flow_imp.id(200290)
,p_button_sequence=>90
,p_button_plug_id=>wwv_flow_imp.id(200040)
,p_button_name=>'VSE'
,p_button_static_id=>'Page200.ButtonsRegion.VSE'
,p_button_action=>'SUBMIT'
,p_button_template_options=>'#DEFAULT#'
,p_button_template_id=>wwv_flow_imp.id(1437822766392171206)
,p_button_image_alt=>'Vse'
,p_grid_new_row=>'N'
,p_grid_new_column=>'Y'
,p_grid_column_span=>1
);
end;
/

begin
wwv_flow_imp_page.create_page_button(
 p_id=>wwv_flow_imp.id(200310)
,p_button_sequence=>100
,p_button_plug_id=>wwv_flow_imp.id(200040)
,p_button_name=>'CELOTNA_OBDELAVA'
,p_button_static_id=>'Page200.ButtonsRegion.CELOTNA_OBDELAVA'
,p_button_action=>'SUBMIT'
,p_button_template_options=>'#DEFAULT#'
,p_button_template_id=>wwv_flow_imp.id(1437822766392171206)
,p_button_image_alt=>'Celotna Obdelava'
,p_grid_new_row=>'N'
,p_grid_new_column=>'Y'
,p_grid_column_span=>1
);
end;
/

begin
wwv_flow_imp_page.create_page_button(
 p_id=>wwv_flow_imp.id(200330)
,p_button_sequence=>110
,p_button_plug_id=>wwv_flow_imp.id(200040)
,p_button_name=>'ID_APPLICATON_TYPE'
,p_button_static_id=>'Page200.ButtonsRegion.ID_APPLICATON_TYPE'
,p_button_action=>'SUBMIT'
,p_button_template_options=>'#DEFAULT#'
,p_button_template_id=>wwv_flow_imp.id(1437822766392171206)
,p_button_image_alt=>'Id Applicaton Type'
,p_grid_new_row=>'N'
,p_grid_new_column=>'Y'
,p_grid_column_span=>1
);
end;
/

begin
wwv_flow_imp_page.create_page_button(
 p_id=>wwv_flow_imp.id(200350)
,p_button_sequence=>120
,p_button_plug_id=>wwv_flow_imp.id(200040)
,p_button_name=>'WHEN-BUTTON-PRESSED'
,p_button_static_id=>'Page200.ButtonsRegion.WHEN-BUTTON-PRESSED'
,p_button_action=>'SUBMIT'
,p_button_template_options=>'#DEFAULT#'
,p_button_template_id=>wwv_flow_imp.id(1437822766392171206)
,p_button_image_alt=>'When-Button-Pressed'
,p_grid_new_row=>'N'
,p_grid_new_column=>'Y'
,p_grid_column_span=>1
);
end;
/

begin
wwv_flow_imp_page.create_page_button(
 p_id=>wwv_flow_imp.id(200370)
,p_button_sequence=>130
,p_button_plug_id=>wwv_flow_imp.id(200040)
,p_button_name=>'B_OK_GENERALI'
,p_button_static_id=>'Page200.ButtonsRegion.B_OK_GENERALI'
,p_button_action=>'SUBMIT'
,p_button_template_options=>'#DEFAULT#'
,p_button_template_id=>wwv_flow_imp.id(1437822766392171206)
,p_button_image_alt=>'B Ok Generali'
,p_grid_new_row=>'N'
,p_grid_new_column=>'Y'
,p_grid_column_span=>1
);
end;
/

begin
wwv_flow_imp_page.create_page_button(
 p_id=>wwv_flow_imp.id(200390)
,p_button_sequence=>140
,p_button_plug_id=>wwv_flow_imp.id(200040)
,p_button_name=>'B_OK_HELP'
,p_button_static_id=>'Page200.ButtonsRegion.B_OK_HELP'
,p_button_action=>'SUBMIT'
,p_button_template_options=>'#DEFAULT#'
,p_button_template_id=>wwv_flow_imp.id(1437822766392171206)
,p_button_image_alt=>'B Ok Help'
,p_grid_new_row=>'N'
,p_grid_new_column=>'Y'
,p_grid_column_span=>1
);
end;
/

-- === PAGE PROCESSES ===
begin
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(200060)
,p_process_sequence=>10
,p_process_point=>'AFTER_SUBMIT'
,p_region_id=>wwv_flow_imp.id(200050)
,p_process_type=>'NATIVE_IG_DML'
,p_process_name=>'B2 - Save Interactive Grid Data'
,p_attribute_01=>'REGION_SOURCE'
,p_attribute_05=>'Y'
,p_attribute_06=>'Y'
,p_attribute_08=>'Y'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_internal_uid=>200060
);
end;
/

begin
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(200080)
,p_process_sequence=>20
,p_process_point=>'AFTER_SUBMIT'
,p_region_id=>wwv_flow_imp.id(200070)
,p_process_type=>'NATIVE_IG_DML'
,p_process_name=>'B3 - Save Interactive Grid Data'
,p_attribute_01=>'REGION_SOURCE'
,p_attribute_05=>'Y'
,p_attribute_06=>'Y'
,p_attribute_08=>'Y'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_internal_uid=>200080
);
end;
/

begin
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(200100)
,p_process_sequence=>30
,p_process_point=>'AFTER_SUBMIT'
,p_region_id=>wwv_flow_imp.id(200090)
,p_process_type=>'NATIVE_IG_DML'
,p_process_name=>'B4 - Save Interactive Grid Data'
,p_attribute_01=>'REGION_SOURCE'
,p_attribute_05=>'Y'
,p_attribute_06=>'Y'
,p_attribute_08=>'Y'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_internal_uid=>200100
);
end;
/

begin
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(200120)
,p_process_sequence=>40
,p_process_point=>'AFTER_SUBMIT'
,p_region_id=>wwv_flow_imp.id(200110)
,p_process_type=>'NATIVE_IG_DML'
,p_process_name=>'B5 - Save Interactive Grid Data'
,p_attribute_01=>'REGION_SOURCE'
,p_attribute_05=>'Y'
,p_attribute_06=>'Y'
,p_attribute_08=>'Y'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_internal_uid=>200120
);
end;
/

begin
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(200140)
,p_process_sequence=>10
,p_process_point=>'ON_SUBMIT_BEFORE_COMPUTATION'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'POLNJENJE_VMESNIKOVProcess'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'-- TODO: migrate from Oracle Forms',
'-- declare ',
'-- 	lb_ok boolean;',
'-- begin',
'--   if show_dane (''Ali res želiš napolniti vse vmesnike ?'') then         ',
'--      /* polnjenje vmesnikov    */',
'--      reinsurance.pack_reins_polnjenje_vmesnikov.pdb_polni_vmesnik_pozav;',
'--      reinsurance.pack_reins_polnjenje_vmesnikov.pdb_polni_vmesnik_pozav_INIS;',
'-- ',
'--      show_msg(''Vmesniki so napolnjeni, preglej error_loge če je vse OK!'','''');',
'--   end if;  ',
'-- end;',
'-- ',
'-- ',
'null; -- placeholder'
))
,p_process_clob_language=>'PLSQL'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_process_when_button_id=>wwv_flow_imp.id(200130)
,p_process_success_message=>'Obdelava Polnjenje Vmesnikov je zakljucena.'
);
end;
/

begin
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(200160)
,p_process_sequence=>20
,p_process_point=>'ON_SUBMIT_BEFORE_COMPUTATION'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'POLNI_SKODEProcess'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'-- TODO: migrate from Oracle Forms',
'-- declare',
'--    pb_ok    boolean;',
'-- begin',
'--     -- polnjeje škod v vmesnike + prenos v reins claims, transactions....',
'--     PACK_REINS_POLNJENJE_VMESNIKOV.pdb_fill_claims_INIS    (pb_ok );',
'--     IF pb_ok THEN',
'--       PACK_REINS_POLNJENJE_VMESNIKOV.pdb_fill_claims    (pb_ok );',
'-- 		END IF;      ',
'--     if not pb_ok then',
'--     	 show_msg(''Pri polnjenju škod je prišlo do napake poglej error_logs!'','''');',
'--     else',
'--     	show_msg(''Vmesniki so napolnjeni, preglej error_loge če je vse OK!'','''');',
'--     end if;',
'--     ',
'-- end;',
'-- ',
'-- ',
'null; -- placeholder'
))
,p_process_clob_language=>'PLSQL'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_process_when_button_id=>wwv_flow_imp.id(200150)
,p_process_success_message=>'Obdelava Polni Skode je zakljucena.'
);
end;
/

begin
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(200180)
,p_process_sequence=>30
,p_process_point=>'ON_SUBMIT_BEFORE_COMPUTATION'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'OBDELAVA_BORDEROJEVProcess'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'-- TODO: migrate from Oracle Forms',
'-- declare ',
'-- 	lb_ok boolean;',
'-- begin',
'--   if show_dane (''Ali res želiš postaviti borderoje ?'') then         ',
'-- ',
'--      reinsurance.pack_create_bordero.pdb_define_risk_sum    (''%''     ',
'--                                                              ,''M''        ',
'--                                                              ,''I'' ',
'--                                                              ,''Y''  /* preracun od zacetka          */',
'--                                                              ,null /* % fakultaivnega pozavarovanja*/',
'--                                                              ,null /* max_pml                      */',
'--                                                          --  ,null /* % provizije                  */',
'--                                                          --  ,null /* znesek min provizije         */',
'--                                                          --  ,null /* % fakultativni pozavarovatelj*/',
'--                                                          --  ,null /* % brokeraze                  */',
'--                                                              ,null /* % delez lnp                  */',
'--                                                              ,:b1.ID_APPLICATON_TYPE',
'--                                                              ,lb_ok);',
'--                                                                                                      ',
'--      if not lb_ok then ',
'--   	    show_msg(''Pri postavitvi borderoja je prišlo do napake!'',''Poglej error loge!'');',
'--      end if;',
'--     ',
'--      go_block (''b2'');',
'--      execute_query;',
'--      go_block (''b1'');',
'--   end if;  ',
'-- end;',
'-- ',
'-- ',
'null; -- placeholder'
))
,p_process_clob_language=>'PLSQL'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_process_when_button_id=>wwv_flow_imp.id(200170)
,p_process_success_message=>'Obdelava Obdelava Borderojev je zakljucena.'
);
end;
/

begin
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(200200)
,p_process_sequence=>40
,p_process_point=>'ON_SUBMIT_BEFORE_COMPUTATION'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'OBDELAVA_VMESNIKOVProcess'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'-- TODO: migrate from Oracle Forms',
'-- declare ',
'-- 	lb_ok boolean;',
'-- begin',
'--   if show_dane (''Ali res želiš obdelati vmesnike ?'') then         ',
'-- ',
'--      pack_risks.pdb_obdelava_vmesnik_pozav(:b1.ID_APPLICATON_TYPE, ''%'' --polica',
'--      , lb_ok);',
'--      if not lb_ok then',
'--   	    show_err(''Pri obdelavi je prišlo do napake!'',''Preveri napake ali pokliči oddelek IT'');',
'--   	 else',
'--   	    show_msg(''Obdelava uspešno zaključena!'','''');',
'--   	 end if;  	 ',
'--   end if;  ',
'-- end;',
'-- ',
'-- ',
'null; -- placeholder'
))
,p_process_clob_language=>'PLSQL'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_process_when_button_id=>wwv_flow_imp.id(200190)
,p_process_success_message=>'Obdelava Obdelava Vmesnikov je zakljucena.'
);
end;
/

begin
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(200220)
,p_process_sequence=>50
,p_process_point=>'ON_SUBMIT_BEFORE_COMPUTATION'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'OBDELAVA_FAKTURProcess'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'-- TODO: migrate from Oracle Forms',
'-- declare ',
'-- 	lb_ok boolean;',
'-- begin',
'--   if show_dane (''Ali res želiš obdelati fakture?'') then         ',
'--      pack_reins_invoices.pdb_reinsrance_invoices (:b1.ID_APPLICATON_TYPE, lb_ok);',
'-- ',
'--      if not lb_ok then ',
'--   	    show_msg(''Pri obdelavi faktur je prišlo do napake!'',''Poglej error loge!'');',
'--      ELSE',
'--      	  show_msg(''Obdelava faktur je zakljucena!'','''');',
'--      end if;',
'--     ',
'--      go_block (''b2'');',
'--      execute_query;',
'--      go_block (''b1'');',
'--   end if;  ',
'-- end;',
'-- ',
'-- ',
'null; -- placeholder'
))
,p_process_clob_language=>'PLSQL'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_process_when_button_id=>wwv_flow_imp.id(200210)
,p_process_success_message=>'Obdelava Obdelava Faktur je zakljucena.'
);
end;
/

begin
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(200240)
,p_process_sequence=>60
,p_process_point=>'ON_SUBMIT_BEFORE_COMPUTATION'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'OBDELAVA_SKODProcess'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'-- TODO: migrate from Oracle Forms',
'-- declare ',
'-- 	lb_ok boolean;',
'-- begin',
'--   if show_dane (''Ali res želiš obdelati nesreče?'') then         ',
'--      pack_reins_claims.pdb_create_claims_entries;',
'--      show_msg( ''Obdelava nesreč je zaključena preveri error_logs!'','''');',
'-- ',
'-- --     if not lb_ok then ',
'-- --  	    show_msg(''Pri obdelavi faktur je prišlo do napake!'',''Poglej error loge!'');',
'-- --     ELSE',
'-- --     	  show_msg(''Obdelava faktur je zakljucena!'','''');',
'-- --     end if;',
'--     ',
'-- --     go_block (''b2'');',
'-- --     execute_query;',
'-- --     go_block (''b1'');',
'--   end if;  ',
'-- end;',
'-- ',
'-- ',
'null; -- placeholder'
))
,p_process_clob_language=>'PLSQL'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_process_when_button_id=>wwv_flow_imp.id(200230)
,p_process_success_message=>'Obdelava Obdelava Skod je zakljucena.'
);
end;
/

begin
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(200260)
,p_process_sequence=>70
,p_process_point=>'ON_SUBMIT_BEFORE_COMPUTATION'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'KONTROLA_SKADENCEProcess'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'-- TODO: migrate from Oracle Forms',
'-- declare ',
'-- 	lb_ok boolean;',
'-- begin',
'--   if show_dane (''Ali res izvesti kontrolo skadence?'') then         ',
'--         pack_risks.pdb_check_risk_sum_due_date (:b1.ID_APPLICATON_TYPE, lb_ok);',
'-- ',
'-- ',
'--      if not lb_ok then ',
'--   	    show_msg(''Pri Kontroli skadence je prišlo do napake!'',''Poglej error loge!'');',
'--      ELSE',
'--      	  show_msg(''Obdelava  je zakljucena!'','''');',
'--      end if;    ',
'--   end if;  ',
'-- end;',
'-- ',
'-- ',
'null; -- placeholder'
))
,p_process_clob_language=>'PLSQL'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_process_when_button_id=>wwv_flow_imp.id(200250)
,p_process_success_message=>'Obdelava Kontrola Skadence je zakljucena.'
);
end;
/

begin
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(200280)
,p_process_sequence=>80
,p_process_point=>'ON_SUBMIT_BEFORE_COMPUTATION'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'NE_OBDELANOProcess'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'-- TODO: migrate from Oracle Forms',
'-- set_block_property (:parameter.p_last_block,default_where, ''obdelano_reinsurance is null'');',
'-- synchronize;',
'-- go_block(:parameter.p_last_block);',
'-- execute_query;   ',
'null; -- placeholder'
))
,p_process_clob_language=>'PLSQL'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_process_when_button_id=>wwv_flow_imp.id(200270)
,p_process_success_message=>'Obdelava Ne Obdelano je zakljucena.'
);
end;
/

begin
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(200300)
,p_process_sequence=>90
,p_process_point=>'ON_SUBMIT_BEFORE_COMPUTATION'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'VSEProcess'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'-- TODO: migrate from Oracle Forms',
'-- DECLARE',
'-- 	  tp_nm   VARCHAR2(30);',
'-- 	  tp_id   TAB_PAGE;',
'-- 	  tp_lbl  VARCHAR2(30);',
'-- begin',
'--  /*',
'--     BEGIN',
'-- 	     tp_nm  := :SYSTEM.TAB_NEW_PAGE;',
'-- 	     tp_id  := FIND_TAB_PAGE(tp_nm);',
'-- 	     tp_lbl := GET_TAB_PAGE_PROPERTY(tp_id, label);',
'--        show_msg(tp_lbl||'' ''||tp_nm,'''');',
'--    exception',
'-- 	    when others then ',
'--       tp_nm := ''VMESNIK_RIZIKI'';',
'--    END;',
'-- if     tp_nm = ''VMESNIK_RIZIKI'' then',
'-- 	     :parameter.p_last_block := ''b1'';',
'-- elsif  tp_nm = ''VMESNIK_SKODE'' then',
'-- 	  :parameter.p_last_block := ''b2'';',
'-- elsif  tp_nm = ''VMESNIK_SKODE_TRANSAKCIJE'' then',
'-- 	  :parameter.p_last_block := ''b3'';	  ',
'-- elsif  tp_nm = ''VMESNIK_ZAVAROVANI_OBJEKTI'' then',
'-- 	  :parameter.p_last_block := ''b4'';	  ',
'-- end if;	',
'-- */',
'--      set_block_property (:parameter.p_last_block,default_where,'''');',
'--      synchronize;',
'--      go_block(:parameter.p_last_block);',
'--      execute_query;   ',
'-- ',
'-- end;',
'null; -- placeholder'
))
,p_process_clob_language=>'PLSQL'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_process_when_button_id=>wwv_flow_imp.id(200290)
,p_process_success_message=>'Obdelava Vse je zakljucena.'
);
end;
/

begin
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(200320)
,p_process_sequence=>100
,p_process_point=>'ON_SUBMIT_BEFORE_COMPUTATION'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'CELOTNA_OBDELAVAProcess'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'-- TODO: migrate from Oracle Forms',
'-- declare ',
'-- 	lb_ok boolean;',
'-- begin',
'--   if show_dane (''Ali res izvesti celotno obdelavo?'') then         ',
'--         pack_reins_polnjenje_vmesnikov.pdb_dnevna_obdelava (''N'',:b1.ID_APPLICATON_TYPE);',
'--      	  show_msg(''Obdelava  je zakljucena!'',''Preveri error loge'');     ',
'--   end if;  ',
'-- end;',
'-- ',
'-- ',
'null; -- placeholder'
))
,p_process_clob_language=>'PLSQL'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_process_when_button_id=>wwv_flow_imp.id(200310)
,p_process_success_message=>'Obdelava Celotna Obdelava je zakljucena.'
);
end;
/

begin
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(200340)
,p_process_sequence=>110
,p_process_point=>'ON_SUBMIT_BEFORE_COMPUTATION'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'ID_APPLICATON_TYPEProcess'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'-- TODO: migrate from Oracle Forms',
'-- declare ',
'-- 	lb_ok boolean;',
'-- begin',
'--   if show_dane (''Ali res izvesti celotno obdelavo?'') then         ',
'--         pack_reins_polnjenje_vmesnikov.pdb_dnevna_obdelava (''N'',:b1.ID_APPLICATON_TYPE);',
'--      	  show_msg(''Obdelava  je zakljucena!'',''Preveri error loge'');     ',
'--   end if;  ',
'-- end;',
'-- ',
'-- ',
'null; -- placeholder'
))
,p_process_clob_language=>'PLSQL'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_process_when_button_id=>wwv_flow_imp.id(200330)
,p_process_success_message=>'Obdelava Id Applicaton Type je zakljucena.'
);
end;
/

begin
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(200360)
,p_process_sequence=>120
,p_process_point=>'ON_SUBMIT_BEFORE_COMPUTATION'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'WHEN-BUTTON-PRESSEDProcess'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'-- TODO: migrate from Oracle Forms',
'-- -- (empty trigger)',
'null; -- placeholder'
))
,p_process_clob_language=>'PLSQL'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_process_when_button_id=>wwv_flow_imp.id(200350)
,p_process_success_message=>'Obdelava When-Button-Pressed je zakljucena.'
);
end;
/

begin
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(200380)
,p_process_sequence=>130
,p_process_point=>'ON_SUBMIT_BEFORE_COMPUTATION'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'B_OK_GENERALIProcess'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'-- TODO: migrate from Oracle Forms',
'-- -- (empty trigger)',
'null; -- placeholder'
))
,p_process_clob_language=>'PLSQL'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_process_when_button_id=>wwv_flow_imp.id(200370)
,p_process_success_message=>'Obdelava B Ok Generali je zakljucena.'
);
end;
/

begin
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(200400)
,p_process_sequence=>140
,p_process_point=>'ON_SUBMIT_BEFORE_COMPUTATION'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'B_OK_HELPProcess'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'-- TODO: migrate from Oracle Forms',
'-- -- (empty trigger)',
'null; -- placeholder'
))
,p_process_clob_language=>'PLSQL'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_process_when_button_id=>wwv_flow_imp.id(200390)
,p_process_success_message=>'Obdelava B Ok Help je zakljucena.'
);
end;
/

-- === FORM-LEVEL TRIGGERS (reference only) ===
-- Trigger: KEY-CLRFRM
--   NULL
--
-- Trigger: ON-ERROR
--   NULL
--
-- Trigger: ON-MESSAGE
--   NULL
--
-- Trigger: KEY-HELP
--   NULL
--
-- Trigger: KEY-MENU
--   NULL
--
-- Trigger: PRE-BLOCK
--   NULL
--
-- Trigger: PRE-FORM
--   NULL
--
-- Trigger: POST-FORM
--   NULL
--
-- Trigger: WHEN-FORM-NAVIGATE
--   NULL
--
-- Trigger: WHEN-MOUSE-DOUBLECLICK
--   NULL
--
-- Trigger: WHEN-TIMER-EXPIRED
--   NULL
--
-- Trigger: WHEN-WINDOW-CLOSED
--   NULL
--
-- Trigger: WHEN-WINDOW-DEACTIVATED
--   NULL
--
-- Trigger: WHEN-WINDOW-RESIZED
--   NULL
--
begin
wwv_flow_imp.import_end(p_auto_install_sup_obj => nvl(wwv_flow_application_install.get_auto_install_sup_obj, false)
);
--commit;
end;
/
set verify on feedback on define on
prompt  ...done
