-- ============================================================
-- APEX page export generated by apex_gen.py
-- Form:        VMESNIKI_POZAVAROVANJE (VMESNIKI_POZAVAROVANJE)
-- Application: 117
-- Generated:   2026-04-21 10:23:59
-- APEX:        24.2.13
-- Layout:      single page per form, multiple regions per block
-- ============================================================

set define off
set verify off

begin
  wwv_flow_imp.import_begin(
    p_version_yyyy_mm_dd => '2024.10.31',
    p_release            => '24.2.13',
    p_default_workspace_id => 64215835499680511,
    p_default_application_id => 117,
    p_default_id_offset  => 0,
    p_default_owner      => 'Y055490'
  );
end;
/

-- Page 100: FORM 'VMESNIKI_POZAVAROVANJE'
prompt --application/pages/page_00100
begin
wwv_flow_imp_page.create_page(
 p_id                  => 100,
 p_name                => 'VMESNIKI_POZAVAROVANJE',
 p_step_title          => 'VMESNIKI_POZAVAROVANJE',
 p_autocomplete_on_off => 'OFF',
 p_page_template_options => '#DEFAULT#',
 p_last_updated_by     => 'GENERATED',
 p_last_upd_yyyymmddhh24miss => '20260421102358'
);
end;
/

-- Region on page 100: CONTROL_BLOCK 'B1'
begin
wwv_flow_imp_page.create_page_plug(
 p_id                       => wwv_flow_imp.id(10010),
 p_plug_name                => 'B1',
 p_region_template_options  => '#DEFAULT#',
 p_plug_display_sequence    => 10,
 p_include_in_reg_disp_sel_yn => 'Y',
 p_plug_source              => null,
 p_plug_source_type         => 'NATIVE_STATIC_CONTENT'
);
end;
/

begin
wwv_flow_imp_page.create_page_button(
 p_id                     => wwv_flow_imp.id(10020),
 p_flow_step_id           => 100,
 p_button_sequence        => 10,
 p_button_plug_id         => wwv_flow_imp.id(10010),
 p_button_name            => 'POLNJENJE_VMESNIKOV',
 p_button_action          => 'SUBMIT',
 p_button_image_alt       => 'Polnjenje Vmesnikov',
 p_button_position        => 'REGION_TEMPLATE_CLOSE'
);
end;
/

begin
wwv_flow_imp_page.create_page_process(
 p_id                     => wwv_flow_imp.id(10030),
 p_flow_step_id           => 100,
 p_process_sequence       => 10,
 p_process_point          => 'AFTER_SUBMIT',
 p_process_type           => 'NATIVE_PLSQL',
 p_process_name           => 'Process_POLNJENJE_VMESNIKOV',
 p_process_sql_clob       => wwv_flow_string.join(wwv_flow_t_varchar2(
'-- TODO: migrate from Oracle Forms',
'-- declare ',
'-- 	lb_ok boolean;',
'-- begin',
'--   if show_dane (''Ali res želiš napolniti vse vmesnike ?'') then         ',
'--      /* polnjenje vmesnikov    */',
'--      reinsurance.pack_reins_polnjenje_vmesnikov.pdb_polni_vmesnik_pozav;',
'--      reinsurance.pack_reins_polnjenje_vmesnikov.pdb_polni_vmesnik_pozav_INIS;',
'-- ',
'--      show_msg(''Vmesniki so napolnjeni, preglej error_loge če je vse OK!'','''');',
'--   end if;  ',
'-- end;',
'-- ',
'-- ',
'null; -- placeholder'
)),
 p_process_when_button_id => wwv_flow_imp.id(10020),
 p_error_display_location => 'INLINE_IN_NOTIFICATION'
);
end;
/

begin
wwv_flow_imp_page.create_page_button(
 p_id                     => wwv_flow_imp.id(10040),
 p_flow_step_id           => 100,
 p_button_sequence        => 20,
 p_button_plug_id         => wwv_flow_imp.id(10010),
 p_button_name            => 'POLNI_SKODE',
 p_button_action          => 'SUBMIT',
 p_button_image_alt       => 'Polni Skode',
 p_button_position        => 'REGION_TEMPLATE_CLOSE'
);
end;
/

begin
wwv_flow_imp_page.create_page_process(
 p_id                     => wwv_flow_imp.id(10050),
 p_flow_step_id           => 100,
 p_process_sequence       => 20,
 p_process_point          => 'AFTER_SUBMIT',
 p_process_type           => 'NATIVE_PLSQL',
 p_process_name           => 'Process_POLNI_SKODE',
 p_process_sql_clob       => wwv_flow_string.join(wwv_flow_t_varchar2(
'-- TODO: migrate from Oracle Forms',
'-- declare',
'--    pb_ok    boolean;',
'-- begin',
'--     -- polnjeje škod v vmesnike + prenos v reins claims, transactions....',
'--     PACK_REINS_POLNJENJE_VMESNIKOV.pdb_fill_claims_INIS    (pb_ok );',
'--     IF pb_ok THEN',
'--       PACK_REINS_POLNJENJE_VMESNIKOV.pdb_fill_claims    (pb_ok );',
'-- 		END IF;      ',
'--     if not pb_ok then',
'--     	 show_msg(''Pri polnjenju škod je prišlo do napake poglej error_logs!'','''');',
'--     else',
'--     	show_msg(''Vmesniki so napolnjeni, preglej error_loge če je vse OK!'','''');',
'--     end if;',
'--     ',
'-- end;',
'-- ',
'-- ',
'null; -- placeholder'
)),
 p_process_when_button_id => wwv_flow_imp.id(10040),
 p_error_display_location => 'INLINE_IN_NOTIFICATION'
);
end;
/

begin
wwv_flow_imp_page.create_page_button(
 p_id                     => wwv_flow_imp.id(10060),
 p_flow_step_id           => 100,
 p_button_sequence        => 30,
 p_button_plug_id         => wwv_flow_imp.id(10010),
 p_button_name            => 'OBDELAVA_BORDEROJEV',
 p_button_action          => 'SUBMIT',
 p_button_image_alt       => 'Obdelava Borderojev',
 p_button_position        => 'REGION_TEMPLATE_CLOSE'
);
end;
/

begin
wwv_flow_imp_page.create_page_process(
 p_id                     => wwv_flow_imp.id(10070),
 p_flow_step_id           => 100,
 p_process_sequence       => 30,
 p_process_point          => 'AFTER_SUBMIT',
 p_process_type           => 'NATIVE_PLSQL',
 p_process_name           => 'Process_OBDELAVA_BORDEROJEV',
 p_process_sql_clob       => wwv_flow_string.join(wwv_flow_t_varchar2(
'-- TODO: migrate from Oracle Forms',
'-- declare ',
'-- 	lb_ok boolean;',
'-- begin',
'--   if show_dane (''Ali res želiš postaviti borderoje ?'') then         ',
'-- ',
'--      reinsurance.pack_create_bordero.pdb_define_risk_sum    (''%''     ',
'--                                                              ,''M''        ',
'--                                                              ,''I'' ',
'--                                                              ,''Y''  /* preracun od zacetka          */',
'--                                                              ,null /* % fakultaivnega pozavarovanja*/',
'--                                                              ,null /* max_pml                      */',
'--                                                          --  ,null /* % provizije                  */',
'--                                                          --  ,null /* znesek min provizije         */',
'--                                                          --  ,null /* % fakultativni pozavarovatelj*/',
'--                                                          --  ,null /* % brokeraze                  */',
'--                                                              ,null /* % delez lnp                  */',
'--                                                              ,:b1.ID_APPLICATON_TYPE',
'--                                                              ,lb_ok);',
'--                                                                                                      ',
'--      if not lb_ok then ',
'--   	    show_msg(''Pri postavitvi borderoja je prišlo do napake!'',''Poglej error loge!'');',
'--      end if;',
'--     ',
'--      go_block (''b2'');',
'--      execute_query;',
'--      go_block (''b1'');',
'--   end if;  ',
'-- end;',
'-- ',
'-- ',
'null; -- placeholder'
)),
 p_process_when_button_id => wwv_flow_imp.id(10060),
 p_error_display_location => 'INLINE_IN_NOTIFICATION'
);
end;
/

begin
wwv_flow_imp_page.create_page_button(
 p_id                     => wwv_flow_imp.id(10080),
 p_flow_step_id           => 100,
 p_button_sequence        => 40,
 p_button_plug_id         => wwv_flow_imp.id(10010),
 p_button_name            => 'OBDELAVA_VMESNIKOV',
 p_button_action          => 'SUBMIT',
 p_button_image_alt       => 'Obdelava Vmesnikov',
 p_button_position        => 'REGION_TEMPLATE_CLOSE'
);
end;
/

begin
wwv_flow_imp_page.create_page_process(
 p_id                     => wwv_flow_imp.id(10090),
 p_flow_step_id           => 100,
 p_process_sequence       => 40,
 p_process_point          => 'AFTER_SUBMIT',
 p_process_type           => 'NATIVE_PLSQL',
 p_process_name           => 'Process_OBDELAVA_VMESNIKOV',
 p_process_sql_clob       => wwv_flow_string.join(wwv_flow_t_varchar2(
'-- TODO: migrate from Oracle Forms',
'-- declare ',
'-- 	lb_ok boolean;',
'-- begin',
'--   if show_dane (''Ali res želiš obdelati vmesnike ?'') then         ',
'-- ',
'--      pack_risks.pdb_obdelava_vmesnik_pozav(:b1.ID_APPLICATON_TYPE, ''%'' --polica',
'--      , lb_ok);',
'--      if not lb_ok then',
'--   	    show_err(''Pri obdelavi je prišlo do napake!'',''Preveri napake ali pokliči oddelek IT'');',
'--   	 else',
'--   	    show_msg(''Obdelava uspešno zaključena!'','''');',
'--   	 end if;  	 ',
'--   end if;  ',
'-- end;',
'-- ',
'-- ',
'null; -- placeholder'
)),
 p_process_when_button_id => wwv_flow_imp.id(10080),
 p_error_display_location => 'INLINE_IN_NOTIFICATION'
);
end;
/

begin
wwv_flow_imp_page.create_page_button(
 p_id                     => wwv_flow_imp.id(10100),
 p_flow_step_id           => 100,
 p_button_sequence        => 50,
 p_button_plug_id         => wwv_flow_imp.id(10010),
 p_button_name            => 'OBDELAVA_FAKTUR',
 p_button_action          => 'SUBMIT',
 p_button_image_alt       => 'Obdelava Faktur',
 p_button_position        => 'REGION_TEMPLATE_CLOSE'
);
end;
/

begin
wwv_flow_imp_page.create_page_process(
 p_id                     => wwv_flow_imp.id(10110),
 p_flow_step_id           => 100,
 p_process_sequence       => 50,
 p_process_point          => 'AFTER_SUBMIT',
 p_process_type           => 'NATIVE_PLSQL',
 p_process_name           => 'Process_OBDELAVA_FAKTUR',
 p_process_sql_clob       => wwv_flow_string.join(wwv_flow_t_varchar2(
'-- TODO: migrate from Oracle Forms',
'-- declare ',
'-- 	lb_ok boolean;',
'-- begin',
'--   if show_dane (''Ali res želiš obdelati fakture?'') then         ',
'--      pack_reins_invoices.pdb_reinsrance_invoices (:b1.ID_APPLICATON_TYPE, lb_ok);',
'-- ',
'--      if not lb_ok then ',
'--   	    show_msg(''Pri obdelavi faktur je prišlo do napake!'',''Poglej error loge!'');',
'--      ELSE',
'--      	  show_msg(''Obdelava faktur je zakljucena!'','''');',
'--      end if;',
'--     ',
'--      go_block (''b2'');',
'--      execute_query;',
'--      go_block (''b1'');',
'--   end if;  ',
'-- end;',
'-- ',
'-- ',
'null; -- placeholder'
)),
 p_process_when_button_id => wwv_flow_imp.id(10100),
 p_error_display_location => 'INLINE_IN_NOTIFICATION'
);
end;
/

begin
wwv_flow_imp_page.create_page_button(
 p_id                     => wwv_flow_imp.id(10120),
 p_flow_step_id           => 100,
 p_button_sequence        => 60,
 p_button_plug_id         => wwv_flow_imp.id(10010),
 p_button_name            => 'OBDELAVA_SKOD',
 p_button_action          => 'SUBMIT',
 p_button_image_alt       => 'Obdelava Skod',
 p_button_position        => 'REGION_TEMPLATE_CLOSE'
);
end;
/

begin
wwv_flow_imp_page.create_page_process(
 p_id                     => wwv_flow_imp.id(10130),
 p_flow_step_id           => 100,
 p_process_sequence       => 60,
 p_process_point          => 'AFTER_SUBMIT',
 p_process_type           => 'NATIVE_PLSQL',
 p_process_name           => 'Process_OBDELAVA_SKOD',
 p_process_sql_clob       => wwv_flow_string.join(wwv_flow_t_varchar2(
'-- TODO: migrate from Oracle Forms',
'-- declare ',
'-- 	lb_ok boolean;',
'-- begin',
'--   if show_dane (''Ali res želiš obdelati nesreče?'') then         ',
'--      pack_reins_claims.pdb_create_claims_entries;',
'--      show_msg( ''Obdelava nesreč je zaključena preveri error_logs!'','''');',
'-- ',
'-- --     if not lb_ok then ',
'-- --  	    show_msg(''Pri obdelavi faktur je prišlo do napake!'',''Poglej error loge!'');',
'-- --     ELSE',
'-- --     	  show_msg(''Obdelava faktur je zakljucena!'','''');',
'-- --     end if;',
'--     ',
'-- --     go_block (''b2'');',
'-- --     execute_query;',
'-- --     go_block (''b1'');',
'--   end if;  ',
'-- end;',
'-- ',
'-- ',
'null; -- placeholder'
)),
 p_process_when_button_id => wwv_flow_imp.id(10120),
 p_error_display_location => 'INLINE_IN_NOTIFICATION'
);
end;
/

begin
wwv_flow_imp_page.create_page_button(
 p_id                     => wwv_flow_imp.id(10140),
 p_flow_step_id           => 100,
 p_button_sequence        => 70,
 p_button_plug_id         => wwv_flow_imp.id(10010),
 p_button_name            => 'KONTROLA_SKADENCE',
 p_button_action          => 'SUBMIT',
 p_button_image_alt       => 'Kontrola Skadence',
 p_button_position        => 'REGION_TEMPLATE_CLOSE'
);
end;
/

begin
wwv_flow_imp_page.create_page_process(
 p_id                     => wwv_flow_imp.id(10150),
 p_flow_step_id           => 100,
 p_process_sequence       => 70,
 p_process_point          => 'AFTER_SUBMIT',
 p_process_type           => 'NATIVE_PLSQL',
 p_process_name           => 'Process_KONTROLA_SKADENCE',
 p_process_sql_clob       => wwv_flow_string.join(wwv_flow_t_varchar2(
'-- TODO: migrate from Oracle Forms',
'-- declare ',
'-- 	lb_ok boolean;',
'-- begin',
'--   if show_dane (''Ali res izvesti kontrolo skadence?'') then         ',
'--         pack_risks.pdb_check_risk_sum_due_date (:b1.ID_APPLICATON_TYPE, lb_ok);',
'-- ',
'-- ',
'--      if not lb_ok then ',
'--   	    show_msg(''Pri Kontroli skadence je prišlo do napake!'',''Poglej error loge!'');',
'--      ELSE',
'--      	  show_msg(''Obdelava  je zakljucena!'','''');',
'--      end if;    ',
'--   end if;  ',
'-- end;',
'-- ',
'-- ',
'null; -- placeholder'
)),
 p_process_when_button_id => wwv_flow_imp.id(10140),
 p_error_display_location => 'INLINE_IN_NOTIFICATION'
);
end;
/

begin
wwv_flow_imp_page.create_page_button(
 p_id                     => wwv_flow_imp.id(10160),
 p_flow_step_id           => 100,
 p_button_sequence        => 80,
 p_button_plug_id         => wwv_flow_imp.id(10010),
 p_button_name            => 'NE_OBDELANO',
 p_button_action          => 'SUBMIT',
 p_button_image_alt       => 'Ne Obdelano',
 p_button_position        => 'REGION_TEMPLATE_CLOSE'
);
end;
/

begin
wwv_flow_imp_page.create_page_process(
 p_id                     => wwv_flow_imp.id(10170),
 p_flow_step_id           => 100,
 p_process_sequence       => 80,
 p_process_point          => 'AFTER_SUBMIT',
 p_process_type           => 'NATIVE_PLSQL',
 p_process_name           => 'Process_NE_OBDELANO',
 p_process_sql_clob       => wwv_flow_string.join(wwv_flow_t_varchar2(
'-- TODO: migrate from Oracle Forms',
'-- set_block_property (:parameter.p_last_block,default_where, ''obdelano_reinsurance is null'');',
'-- synchronize;',
'-- go_block(:parameter.p_last_block);',
'-- execute_query;   ',
'null; -- placeholder'
)),
 p_process_when_button_id => wwv_flow_imp.id(10160),
 p_error_display_location => 'INLINE_IN_NOTIFICATION'
);
end;
/

begin
wwv_flow_imp_page.create_page_button(
 p_id                     => wwv_flow_imp.id(10180),
 p_flow_step_id           => 100,
 p_button_sequence        => 90,
 p_button_plug_id         => wwv_flow_imp.id(10010),
 p_button_name            => 'VSE',
 p_button_action          => 'SUBMIT',
 p_button_image_alt       => 'Vse',
 p_button_position        => 'REGION_TEMPLATE_CLOSE'
);
end;
/

begin
wwv_flow_imp_page.create_page_process(
 p_id                     => wwv_flow_imp.id(10190),
 p_flow_step_id           => 100,
 p_process_sequence       => 90,
 p_process_point          => 'AFTER_SUBMIT',
 p_process_type           => 'NATIVE_PLSQL',
 p_process_name           => 'Process_VSE',
 p_process_sql_clob       => wwv_flow_string.join(wwv_flow_t_varchar2(
'-- TODO: migrate from Oracle Forms',
'-- DECLARE',
'-- 	  tp_nm   VARCHAR2(30);',
'-- 	  tp_id   TAB_PAGE;',
'-- 	  tp_lbl  VARCHAR2(30);',
'-- begin',
'--  /*',
'--     BEGIN',
'-- 	     tp_nm  := :SYSTEM.TAB_NEW_PAGE;',
'-- 	     tp_id  := FIND_TAB_PAGE(tp_nm);',
'-- 	     tp_lbl := GET_TAB_PAGE_PROPERTY(tp_id, label);',
'--        show_msg(tp_lbl||'' ''||tp_nm,'''');',
'--    exception',
'-- 	    when others then ',
'--       tp_nm := ''VMESNIK_RIZIKI'';',
'--    END;',
'-- if     tp_nm = ''VMESNIK_RIZIKI'' then',
'-- 	     :parameter.p_last_block := ''b1'';',
'-- elsif  tp_nm = ''VMESNIK_SKODE'' then',
'-- 	  :parameter.p_last_block := ''b2'';',
'-- elsif  tp_nm = ''VMESNIK_SKODE_TRANSAKCIJE'' then',
'-- 	  :parameter.p_last_block := ''b3'';	  ',
'-- elsif  tp_nm = ''VMESNIK_ZAVAROVANI_OBJEKTI'' then',
'-- 	  :parameter.p_last_block := ''b4'';	  ',
'-- end if;	',
'-- */',
'--      set_block_property (:parameter.p_last_block,default_where,'''');',
'--      synchronize;',
'--      go_block(:parameter.p_last_block);',
'--      execute_query;   ',
'-- ',
'-- end;',
'null; -- placeholder'
)),
 p_process_when_button_id => wwv_flow_imp.id(10180),
 p_error_display_location => 'INLINE_IN_NOTIFICATION'
);
end;
/

begin
wwv_flow_imp_page.create_page_button(
 p_id                     => wwv_flow_imp.id(10200),
 p_flow_step_id           => 100,
 p_button_sequence        => 100,
 p_button_plug_id         => wwv_flow_imp.id(10010),
 p_button_name            => 'CELOTNA_OBDELAVA',
 p_button_action          => 'SUBMIT',
 p_button_image_alt       => 'Celotna Obdelava',
 p_button_position        => 'REGION_TEMPLATE_CLOSE'
);
end;
/

begin
wwv_flow_imp_page.create_page_process(
 p_id                     => wwv_flow_imp.id(10210),
 p_flow_step_id           => 100,
 p_process_sequence       => 100,
 p_process_point          => 'AFTER_SUBMIT',
 p_process_type           => 'NATIVE_PLSQL',
 p_process_name           => 'Process_CELOTNA_OBDELAVA',
 p_process_sql_clob       => wwv_flow_string.join(wwv_flow_t_varchar2(
'-- TODO: migrate from Oracle Forms',
'-- declare ',
'-- 	lb_ok boolean;',
'-- begin',
'--   if show_dane (''Ali res izvesti celotno obdelavo?'') then         ',
'--         pack_reins_polnjenje_vmesnikov.pdb_dnevna_obdelava (''N'',:b1.ID_APPLICATON_TYPE);',
'--      	  show_msg(''Obdelava  je zakljucena!'',''Preveri error loge'');     ',
'--   end if;  ',
'-- end;',
'-- ',
'-- ',
'null; -- placeholder'
)),
 p_process_when_button_id => wwv_flow_imp.id(10200),
 p_error_display_location => 'INLINE_IN_NOTIFICATION'
);
end;
/

begin
wwv_flow_imp_page.create_page_button(
 p_id                     => wwv_flow_imp.id(10220),
 p_flow_step_id           => 100,
 p_button_sequence        => 110,
 p_button_plug_id         => wwv_flow_imp.id(10010),
 p_button_name            => 'ID_APPLICATON_TYPE',
 p_button_action          => 'SUBMIT',
 p_button_image_alt       => 'Id Applicaton Type',
 p_button_position        => 'REGION_TEMPLATE_CLOSE'
);
end;
/

begin
wwv_flow_imp_page.create_page_process(
 p_id                     => wwv_flow_imp.id(10230),
 p_flow_step_id           => 100,
 p_process_sequence       => 110,
 p_process_point          => 'AFTER_SUBMIT',
 p_process_type           => 'NATIVE_PLSQL',
 p_process_name           => 'Process_ID_APPLICATON_TYPE',
 p_process_sql_clob       => wwv_flow_string.join(wwv_flow_t_varchar2(
'-- TODO: migrate from Oracle Forms',
'-- declare ',
'-- 	lb_ok boolean;',
'-- begin',
'--   if show_dane (''Ali res izvesti celotno obdelavo?'') then         ',
'--         pack_reins_polnjenje_vmesnikov.pdb_dnevna_obdelava (''N'',:b1.ID_APPLICATON_TYPE);',
'--      	  show_msg(''Obdelava  je zakljucena!'',''Preveri error loge'');     ',
'--   end if;  ',
'-- end;',
'-- ',
'-- ',
'null; -- placeholder'
)),
 p_process_when_button_id => wwv_flow_imp.id(10220),
 p_error_display_location => 'INLINE_IN_NOTIFICATION'
);
end;
/

-- Region on page 100: DATA_BLOCK 'B2' -> VMESNIK_POZAVAROVANJE
begin
wwv_flow_imp_page.create_page_plug(
 p_id                       => wwv_flow_imp.id(10240),
 p_plug_name                => 'VMESNIK_POZAVAROVANJE',
 p_region_template_options  => '#DEFAULT#',
 p_plug_display_sequence    => 20,
 p_include_in_reg_disp_sel_yn => 'Y',
 p_plug_source              => 'SELECT * FROM VMESNIK_POZAVAROVANJE',
 p_plug_source_type         => 'NATIVE_IR'
);
end;
/

begin
wwv_flow_imp_page.create_page_process(
 p_id                     => wwv_flow_imp.id(10250),
 p_flow_step_id           => 100,
 p_process_sequence       => 120,
 p_process_point          => 'AFTER_SUBMIT',
 p_process_type           => 'NATIVE_PLSQL',
 p_process_name           => 'B2: WHEN-NEW-BLOCK-INSTANCE',
 p_process_sql_clob       => wwv_flow_string.join(wwv_flow_t_varchar2(
'-- TODO: migrate from Oracle Forms',
'-- begin',
'--   :parameter.P_LAST_BLOCK := ''b2'';',
'-- exception when others then',
'-- 	show_msg(''nakaj ni ok'','''');',
'-- end;',
'-- ',
'null; -- placeholder'
)),
 p_error_display_location => 'INLINE_IN_NOTIFICATION'
);
end;
/

-- Region on page 100: DATA_BLOCK 'B3' -> VMESNIK_SKODE
begin
wwv_flow_imp_page.create_page_plug(
 p_id                       => wwv_flow_imp.id(10260),
 p_plug_name                => 'VMESNIK_SKODE',
 p_region_template_options  => '#DEFAULT#',
 p_plug_display_sequence    => 30,
 p_include_in_reg_disp_sel_yn => 'Y',
 p_plug_source              => 'SELECT * FROM VMESNIK_SKODE',
 p_plug_source_type         => 'NATIVE_IR'
);
end;
/

begin
wwv_flow_imp_page.create_page_process(
 p_id                     => wwv_flow_imp.id(10270),
 p_flow_step_id           => 100,
 p_process_sequence       => 130,
 p_process_point          => 'AFTER_SUBMIT',
 p_process_type           => 'NATIVE_PLSQL',
 p_process_name           => 'B3: WHEN-NEW-BLOCK-INSTANCE',
 p_process_sql_clob       => wwv_flow_string.join(wwv_flow_t_varchar2(
'-- TODO: migrate from Oracle Forms',
'-- begin',
'--   :parameter.P_LAST_BLOCK := ''b3'';',
'-- exception when others then',
'-- 	show_msg(''nakaj ni ok'','''');',
'-- end;',
'-- ',
'null; -- placeholder'
)),
 p_error_display_location => 'INLINE_IN_NOTIFICATION'
);
end;
/

-- Region on page 100: DATA_BLOCK 'B4' -> VMESNIK_SKODE_TRANSAKCIJE
begin
wwv_flow_imp_page.create_page_plug(
 p_id                       => wwv_flow_imp.id(10280),
 p_plug_name                => 'VMESNIK_SKODE_TRANSAKCIJE',
 p_region_template_options  => '#DEFAULT#',
 p_plug_display_sequence    => 40,
 p_include_in_reg_disp_sel_yn => 'Y',
 p_plug_source              => 'SELECT * FROM VMESNIK_SKODE_TRANSAKCIJE',
 p_plug_source_type         => 'NATIVE_IR'
);
end;
/

begin
wwv_flow_imp_page.create_page_process(
 p_id                     => wwv_flow_imp.id(10290),
 p_flow_step_id           => 100,
 p_process_sequence       => 140,
 p_process_point          => 'AFTER_SUBMIT',
 p_process_type           => 'NATIVE_PLSQL',
 p_process_name           => 'B4: WHEN-NEW-BLOCK-INSTANCE',
 p_process_sql_clob       => wwv_flow_string.join(wwv_flow_t_varchar2(
'-- TODO: migrate from Oracle Forms',
'-- begin',
'--   :parameter.P_LAST_BLOCK := ''b4'';',
'-- exception when others then',
'-- 	show_msg(''nakaj ni ok'','''');',
'-- end;',
'-- ',
'null; -- placeholder'
)),
 p_error_display_location => 'INLINE_IN_NOTIFICATION'
);
end;
/

-- Region on page 100: DATA_BLOCK 'B5' -> VMESNIK_ZAVAROVANI_OBJEKTI
begin
wwv_flow_imp_page.create_page_plug(
 p_id                       => wwv_flow_imp.id(10300),
 p_plug_name                => 'VMESNIK_ZAVAROVANI_OBJEKTI',
 p_region_template_options  => '#DEFAULT#',
 p_plug_display_sequence    => 50,
 p_include_in_reg_disp_sel_yn => 'Y',
 p_plug_source              => 'SELECT * FROM VMESNIK_ZAVAROVANI_OBJEKTI',
 p_plug_source_type         => 'NATIVE_IR'
);
end;
/

begin
wwv_flow_imp_page.create_page_process(
 p_id                     => wwv_flow_imp.id(10310),
 p_flow_step_id           => 100,
 p_process_sequence       => 150,
 p_process_point          => 'AFTER_SUBMIT',
 p_process_type           => 'NATIVE_PLSQL',
 p_process_name           => 'B5: WHEN-NEW-BLOCK-INSTANCE',
 p_process_sql_clob       => wwv_flow_string.join(wwv_flow_t_varchar2(
'-- TODO: migrate from Oracle Forms',
'-- begin',
'--   :parameter.P_LAST_BLOCK := ''b5'';',
'-- exception when others then',
'-- 	show_msg(''nakaj ni ok'','''');',
'-- end;',
'-- ',
'null; -- placeholder'
)),
 p_error_display_location => 'INLINE_IN_NOTIFICATION'
);
end;
/

-- Region on page 100: CONTROL_BLOCK 'TOOLBAR'
begin
wwv_flow_imp_page.create_page_plug(
 p_id                       => wwv_flow_imp.id(10320),
 p_plug_name                => 'Toolbar',
 p_region_template_options  => '#DEFAULT#',
 p_plug_display_sequence    => 60,
 p_include_in_reg_disp_sel_yn => 'Y',
 p_plug_source              => null,
 p_plug_source_type         => 'NATIVE_STATIC_CONTENT'
);
end;
/

begin
wwv_flow_imp_page.create_page_button(
 p_id                     => wwv_flow_imp.id(10330),
 p_flow_step_id           => 100,
 p_button_sequence        => 10,
 p_button_plug_id         => wwv_flow_imp.id(10320),
 p_button_name            => 'WHEN-BUTTON-PRESSED',
 p_button_action          => 'SUBMIT',
 p_button_image_alt       => 'When-Button-Pressed',
 p_button_position        => 'REGION_TEMPLATE_CLOSE'
);
end;
/

begin
wwv_flow_imp_page.create_page_process(
 p_id                     => wwv_flow_imp.id(10340),
 p_flow_step_id           => 100,
 p_process_sequence       => 160,
 p_process_point          => 'AFTER_SUBMIT',
 p_process_type           => 'NATIVE_PLSQL',
 p_process_name           => 'Process_WHEN-BUTTON-PRESSED',
 p_process_sql_clob       => wwv_flow_string.join(wwv_flow_t_varchar2(
'-- TODO: migrate from Oracle Forms',
'-- -- (empty trigger)',
'null; -- placeholder'
)),
 p_process_when_button_id => wwv_flow_imp.id(10330),
 p_error_display_location => 'INLINE_IN_NOTIFICATION'
);
end;
/

begin
wwv_flow_imp_page.create_page_process(
 p_id                     => wwv_flow_imp.id(10350),
 p_flow_step_id           => 100,
 p_process_sequence       => 170,
 p_process_point          => 'AFTER_SUBMIT',
 p_process_type           => 'NATIVE_PLSQL',
 p_process_name           => 'TOOLBAR: WHEN-MOUSE-LEAVE',
 p_process_sql_clob       => wwv_flow_string.join(wwv_flow_t_varchar2(
'-- TODO: migrate from Oracle Forms',
'-- -- (empty trigger)',
'null; -- placeholder'
)),
 p_error_display_location => 'INLINE_IN_NOTIFICATION'
);
end;
/

begin
wwv_flow_imp_page.create_page_process(
 p_id                     => wwv_flow_imp.id(10360),
 p_flow_step_id           => 100,
 p_process_sequence       => 180,
 p_process_point          => 'AFTER_SUBMIT',
 p_process_type           => 'NATIVE_PLSQL',
 p_process_name           => 'TOOLBAR: WHEN-MOUSE-ENTER',
 p_process_sql_clob       => wwv_flow_string.join(wwv_flow_t_varchar2(
'-- TODO: migrate from Oracle Forms',
'-- -- (empty trigger)',
'null; -- placeholder'
)),
 p_error_display_location => 'INLINE_IN_NOTIFICATION'
);
end;
/

-- Region on page 100: CONTROL_BLOCK 'B0'
begin
wwv_flow_imp_page.create_page_plug(
 p_id                       => wwv_flow_imp.id(10370),
 p_plug_name                => 'B0',
 p_region_template_options  => '#DEFAULT#',
 p_plug_display_sequence    => 70,
 p_include_in_reg_disp_sel_yn => 'Y',
 p_plug_source              => null,
 p_plug_source_type         => 'NATIVE_STATIC_CONTENT'
);
end;
/

begin
wwv_flow_imp_page.create_page_button(
 p_id                     => wwv_flow_imp.id(10380),
 p_flow_step_id           => 100,
 p_button_sequence        => 10,
 p_button_plug_id         => wwv_flow_imp.id(10370),
 p_button_name            => 'B_OK_GENERALI',
 p_button_action          => 'SUBMIT',
 p_button_image_alt       => 'B Ok Generali',
 p_button_position        => 'REGION_TEMPLATE_CLOSE'
);
end;
/

begin
wwv_flow_imp_page.create_page_process(
 p_id                     => wwv_flow_imp.id(10390),
 p_flow_step_id           => 100,
 p_process_sequence       => 190,
 p_process_point          => 'AFTER_SUBMIT',
 p_process_type           => 'NATIVE_PLSQL',
 p_process_name           => 'Process_B_OK_GENERALI',
 p_process_sql_clob       => wwv_flow_string.join(wwv_flow_t_varchar2(
'-- TODO: migrate from Oracle Forms',
'-- -- (empty trigger)',
'null; -- placeholder'
)),
 p_process_when_button_id => wwv_flow_imp.id(10380),
 p_error_display_location => 'INLINE_IN_NOTIFICATION'
);
end;
/

begin
wwv_flow_imp_page.create_page_button(
 p_id                     => wwv_flow_imp.id(10400),
 p_flow_step_id           => 100,
 p_button_sequence        => 20,
 p_button_plug_id         => wwv_flow_imp.id(10370),
 p_button_name            => 'B_OK_HELP',
 p_button_action          => 'SUBMIT',
 p_button_image_alt       => 'B Ok Help',
 p_button_position        => 'REGION_TEMPLATE_CLOSE'
);
end;
/

begin
wwv_flow_imp_page.create_page_process(
 p_id                     => wwv_flow_imp.id(10410),
 p_flow_step_id           => 100,
 p_process_sequence       => 200,
 p_process_point          => 'AFTER_SUBMIT',
 p_process_type           => 'NATIVE_PLSQL',
 p_process_name           => 'Process_B_OK_HELP',
 p_process_sql_clob       => wwv_flow_string.join(wwv_flow_t_varchar2(
'-- TODO: migrate from Oracle Forms',
'-- -- (empty trigger)',
'null; -- placeholder'
)),
 p_process_when_button_id => wwv_flow_imp.id(10400),
 p_error_display_location => 'INLINE_IN_NOTIFICATION'
);
end;
/

begin
wwv_flow_imp_page.create_page_process(
 p_id                     => wwv_flow_imp.id(10420),
 p_flow_step_id           => 100,
 p_process_sequence       => 210,
 p_process_point          => 'AFTER_SUBMIT',
 p_process_type           => 'NATIVE_PLSQL',
 p_process_name           => 'B0: KEY-EXIT',
 p_process_sql_clob       => wwv_flow_string.join(wwv_flow_t_varchar2(
'-- TODO: migrate from Oracle Forms',
'-- -- (empty trigger)',
'null; -- placeholder'
)),
 p_error_display_location => 'INLINE_IN_NOTIFICATION'
);
end;
/

-- ============================================================
-- Form-level triggers (reference only, not imported as processes)
-- Trigger: KEY-CLRFRM
--   NULL
--
-- Trigger: ON-ERROR
--   NULL
--
-- Trigger: ON-MESSAGE
--   NULL
--
-- Trigger: KEY-HELP
--   NULL
--
-- Trigger: KEY-MENU
--   NULL
--
-- Trigger: PRE-BLOCK
--   NULL
--
-- Trigger: PRE-FORM
--   NULL
--
-- Trigger: POST-FORM
--   NULL
--
-- Trigger: WHEN-FORM-NAVIGATE
--   NULL
--
-- Trigger: WHEN-MOUSE-DOUBLECLICK
--   NULL
--
-- Trigger: WHEN-TIMER-EXPIRED
--   NULL
--
-- Trigger: WHEN-WINDOW-CLOSED
--   NULL
--
-- Trigger: WHEN-WINDOW-DEACTIVATED
--   NULL
--
-- Trigger: WHEN-WINDOW-RESIZED
--   NULL
--
-- ============================================================

begin
  wwv_flow_imp.import_end(p_auto_install_sup_obj => true);
end;
/

set define on